### ISSUE TITLE
看不到icon图标全是？号

### ISSUE THREAD

**Issue by hujialianghuwei** [czy0729/Bangumi#1]
看不到icon 图标 变成了问号了

**Comment by czy0729** [comment]
你是跑apk看不到icon, 还是开发环境expo看不到icon?
window我不清楚, 假如是mac环境
https://github.com/czy0729/Bangumi#getting-started
把assets/iconfont/vector-icons 跟 node_modules/@expo/vector-icons 合并 , 是合并不是替换
