### ISSUE TITLE
时间胶囊中的描述问题

### ISSUE THREAD

**Issue by AppleSpriter** [czy0729/Bangumi#10]
在时间胶囊中，如果之前标记**看到**一部番的中间集数，比如13集标记看到8话

web端显示 完成了 あっちこっち **8 of 13 话**
mobile端显示 完成了一起一起这里那里

这里不显示具体话数，如果标记**单集看过**的话mobile端能正确显示话数：看过ep.8+该集名称+番剧名
希望能把**看到**具体几话正确的显示在时间胶囊中，不然总感觉有歧义（跟看完全集一样

**Comment by czy0729** [comment]
时间胶囊数据情况异常多且复杂, app内比较早期的功能, 写得不太好, 我重构下

**Comment by czy0729** [comment]
![image](https://user-images.githubusercontent.com/13514316/92882032-2096e400-f442-11ea-85f4-e6cadb187f74.png)
我查了一下, 感觉没发现你说的情况啊, 等一个反馈

**Comment by AppleSpriter** [comment]
![Screenshot_20200911_152554_com czy0729 bangumi](https://user-images.githubusercontent.com/26051275/92883270-4a9cd600-f443-11ea-9a3a-88f2acbda4ea.jpg)

![)PE8{$U$YLP1S4OX@1J53_D](https://user-images.githubusercontent.com/26051275/92883355-5a1c1f00-f443-11ea-92ee-ab212b63c535.png)

![~X7EH)J_0R8CVY4{870_POI](https://user-images.githubusercontent.com/26051275/92883488-78821a80-f443-11ea-93d4-d5beedcf18fe.png)
是这样，网页端有看过和看到两种选项，【看过】是只标记一集，这样显示是没有问题的，【看到】是标记从之前看完的部分到标记的集数，这个选项在手机端时间胶囊中显示的是完成（没说具体集数），但是电脑端是没有问题的

**Comment by czy0729** [comment]
![image](https://user-images.githubusercontent.com/13514316/92962282-4f917200-f4a3-11ea-98b8-083a3f406a91.png)
下个版本
