### ISSUE TITLE
【bug】点击webp图片导致崩溃

### ISSUE THREAD

**Issue by Zao-chen** [czy0729/Bangumi#101]
![Screenshot_2023-05-10-22-19-47-215_com.czy0729.bangumi.jpg](https://github.com/czy0729/Bangumi/assets/77674075/c315fc78-7d1f-4c86-9f68-dc4f4f8d0e13)
就是图片最下面那个图片。
点了以后不是打开浏览器什么的，而是崩溃
我试了一下，只要是webp图像都不行
触发率100％
版本7.13.0
Android9
顺带一提，希望可以添加显示webp图片文件

**Comment by czy0729** [comment]
很清晰，收到
