### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by Manicsteiner** [czy0729/Bangumi#102]
![Screenshot_2023-05-20-09-33-29](https://github.com/czy0729/Bangumi/assets/63437036/ecaf4c0a-1367-4cbf-bc29-c005965d6f1e)
7.14.0版本启动后必定报错，点relaunch和quit均闪退。清除数据也仍然如此。7.13.0及以前版本正常。
系统：安卓8.0.0、EMUI 8.0.0，使用github release armv8安装包

**Comment by czy0729** [comment]
我知道为什么了，可能之后处理还得先打包让你帮忙测试

**Comment by czy0729** [comment]
https://czy0729.lanzouf.com/iw4of0wnti4h
帮忙试试这个

**Comment by Manicsteiner** [comment]
感谢，已经能够正常使用。
