### ISSUE TITLE
[Feature Request]iOS端请求添加每日放送widget

### ISSUE THREAD

**Issue by Aintor** [czy0729/Bangumi#103]
用的Mac侧载的ipa，主要希望看每日放送的信息（而不是已追番剧的放送情况，不然网上很多ics项目可以直接用），希望能出一个widget组件方便查看所有番剧的播出情况。

**Comment by czy0729** [comment]
是mac打错了应该是iphone吗？widget我目前这个框架不太可能实现，我也完全不会原生，曾经看过别人开源过的widget写法，但是应该不太可能走通。只能说先标记。

**Comment by Aintor** [comment]
不是啊，就是Mac，用的playcover侧载的。关于widget其实是可以和iOS兼容的，比如这个侧载的微博
<img width="1038" alt="截屏2023-05-22 10 54 04" src="https://github.com/czy0729/Bangumi/assets/86539564/d33d7fa8-7a05-49de-bc73-3c619549e9e7">

**Comment by czy0729** [comment]
独立数据写个简单点的应该还是有可能的，我研究下，参考下豆瓣

**Comment by Aintor** [comment]
sorry，我刚刚弄错了，我那个是app store下的微博，不能保证侧载一定能使用widget。关于这个研究可以先推迟一下，抱歉了。

**Comment by Aintor** [comment]
sorry，我刚刚弄错了，我那个是app store下的微博，不能保证侧载一定能使用widget。关于这个研究可以先推迟一下，抱歉了。

**Comment by czy0729** [comment]
没什么，我还在等下一次发布会会不会开官方侧载

**Comment by czy0729** [comment]
能不能说一下你期望的组件是什么样子，有什么数据，包括小中大的设计。事实上我在安卓那边研究好了整套流程。。。

**Comment by Aintor** [comment]
我对设计没什么经验，但总归来说，以我的需求希望能有的基本元素有今日放送的时间和内容（包括图片和番剧名称）。
一个想法：
<img width="712" alt="截屏2023-05-24 13 18 36" src="https://github.com/czy0729/Bangumi/assets/86539564/3f361e83-bef5-46e7-a204-3a7ca78a6dd5">
底层是半灰色透明的底板。
因为时间分为固定段（几月几日星期几）和变化段（几点放送），我个人的考虑是，固定段好像没有太大必要加入。把变化时间放在右上角和大多数电子设备显示时间的位置相同。
中间的白色部分是显示番剧放送的地方，一次只显示一块内容，每块内容是当前右上角显示时间点将会放送的动画的所有条目，条目则可以使用典型的左侧封面，右侧内容的显示结构。块可以上下滑动以切换放送时间，滑动的动效可以适当添加。
总的来说这样块和内容的形式有点像知乎的内容浏览，暂时想法是这样，不知道可不可行。
