### ISSUE TITLE
【bug】进度中使用网格模式，游戏点击无效

### ISSUE THREAD

**Issue by Zao-chen** [czy0729/Bangumi#104]
![Screenshot_2023-05-28-23-56-56-266_com.czy0729.bangumi.jpg](https://github.com/czy0729/Bangumi/assets/77674075/73629319-511c-4653-8cc9-e583960b54f8)
如上图，在进度设置中打开了显示游戏，在”全部”视图中，尽管点击了下方的网格图(图中点击了魔女的宴席），上面还是显示”请先点击下方条目”，书籍和动画没有相关情况，只有游戏出现。把进度改到”游戏”视图中，就可以正常点击，只有在”全部”里面不行。
复现方式:概率100％，打开在进度中游戏标签页
版本 7.14.1

**Comment by czy0729** [comment]
https://github.com/czy0729/Bangumi/commit/3f950fa3212eb394af19978d8bfc43d445fb617f
