### ISSUE TITLE
无法安装7.15.0ipa

### ISSUE THREAD

**Issue by jesuxel** [czy0729/Bangumi#105]
![IMG_9889](https://github.com/czy0729/Bangumi/assets/81166629/f084f58e-1dd3-4222-a997-569d2d5df76b)

**Comment by czy0729** [comment]
我有一个朋友用altStore安装也成功
我自己试了一下mac也能成功
我也发现用爱思助手现在居然都不需要越狱, 就能直接安装成功, 甚至还没有7天过期, 你可以去试一下
