### ISSUE TITLE
標籤的顯示字形≠實際字形

### ISSUE THREAD

**Issue by lef-est** [czy0729/Bangumi#106]
現在標籤的顯示字形是跟隨應用設定（比如說繁體）。在修改收藏介面點擊推薦標籤後，實際添加的是源字形。
以下兩種處理都比現狀好一些：
1. 標籤不受應用設定影響 永遠顯示源字形 那至少可以看字面考慮要不要點
2. 讓點擊後添加的標籤跟隨應用設定（也就是多加一層字形轉換） 這個更方便 不過轉換不總是準確

**Comment by czy0729** [comment]
秒懂，这么多年第一次有人提这个，确实是个问题，马上修

**Comment by czy0729** [comment]
我目前打算是按简单的处理，就是按1方案，只是把点击的那个标签使用本来的简体字形（不转换）
不过同样也有其他问题，如果不输入还好，点击简体的来用，但是输入还是繁体的话，按道理一样的标签意思也会变成2个，不过我不打算处理这种问题

**Comment by lef-est** [comment]
> 我目前打算是按简单的处理，就是按1方案，只是把点击的那个标签使用本来的简体字形（不转换） 不过同样也有其他问题，如果不输入还好，点击简体的来用，但是输入还是繁体的话，按道理一样的标签意思也会变成2个，不过我不打算处理这种问题

我也覺得1就行 因為簡繁之外還有日語字形 而且用日語字形標籤的人應該會有很多 如果方案2不考慮日語就很尷尬 而要考慮又很麻煩
但你說的其實我沒怎麼看懂🙈

**Comment by czy0729** [comment]
我只是改了一点，繁体设置开启中，弹出的那个管理框里面的标签改成了不转换成繁体，其余的没变化
