### ISSUE TITLE
一个小细节
关于超展开的下拉刷新建议

### ISSUE THREAD

**Issue by Zao-chen** [czy0729/Bangumi#107]
![Screenshot_2023-06-20-16-17-56-223_com.czy0729.bangumi.jpg](https://github.com/czy0729/Bangumi/assets/77674075/07e16795-ccf4-4966-9806-2008f92ed04c)
如图，菜单上的“条目“字在下拉刷新的小圆圈上面，感觉看的不舒服 建议小圆圈从菜单下面出来，而不是从最顶上
版本7.15.1

**Comment by czy0729** [comment]
你这机子的表现跟我的 MIUI 不一样，位置开始应该是一样，但是我这边上面的 Tab 会遮住这个圆圈所以没这样。
我看看能不能调。
