### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by AndyLZC** [czy0729/Bangumi#11]
npm ERR! code ENOENT
npm ERR! syscall stat
npm ERR! path /Users/andy/Desktop/react-native/Bangumi/sdk-39.0.3.tar.gz
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, stat '/Users/andy/Desktop/react-native/Bangumi/sdk-39.0.3.tar.gz'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andy/.npm/_logs/2020-10-25T10_24_42_842Z-debug.log

**Comment by czy0729** [comment]
官方expo sdk39有严重bug 你可以把package.json的react-native版本改成~0.62.2试试,
或者直接clone 4.0.0的版本先用

**Comment by AndyLZC** [comment]
改成~0.63.2才匹配版本

但是在expo developer tools还是启动失败了
ERROR
08:16
Building JavaScript bundle: error
ERROR
08:16
Unable to resolve "./Libraries/YellowBox/YellowBox" from "node_modules/react-native/index.js"

**Comment by czy0729** [comment]
https://github.com/czy0729/Bangumi/tree/4.0.1
想跑起来先用tag@4.0.1去试吧, 4.0.1跟现在的4.2.0其实功能没差多少
在expo没更新sdk40之前, 感觉都要改很多地方, 我也是升级到39才踩到坑的也浪费了我1整天调bug
