### ISSUE TITLE
[BUG] v8.1.0 x86-64 apk 在AVD和WSA上均闪退

### ISSUE THREAD

**Issue by Manicsteiner** [czy0729/Bangumi#113]
如题，安装后均为一闪启动画面立即闪退，没有留下任何信息。改为使用armv8a apk可以正常使用。
AVD  Android emulator version 32.1.14.0 (build_id 10330179)  Android 13.0  Google APIs  x86_64
WSA  2305.40000.6.0  Android 13

**Comment by czy0729** [comment]
手机模拟器肯定使用v8a的，只有win11桌面用的会是x86。还是说我理解错了问题？

**Comment by Manicsteiner** [comment]
WSA就是指win11子系统。另外AVD是Android Studio附带的模拟器，也原生支持x86-64，但是x86-64 apk都是闪退。安装armv8a apk可以正常运行。

**Comment by czy0729** [comment]
感谢科普，让我知道现在的模拟器也能跑x86。不过这能不能跑已经不是我能控制的能力范围了，基本所有打包的相关事项都是框架自动带的，应该是无法修复的。

**Comment by Manicsteiner** [comment]
8.3.0 / 8.3.1 x64版 已可以正常运行。
