### ISSUE TITLE
[Bug]超展开帖子回复框工具栏被遮挡

### ISSUE THREAD

**Issue by Manicsteiner** [czy0729/Bangumi#116]
![Screenshot_2023-10-02-15-49-27-767_com czy0729 bangumi](https://github.com/czy0729/Bangumi/assets/63437036/9c54307f-6b20-4500-be5e-5d40e26cc448)
![Screenshot_20231002-155855](https://github.com/czy0729/Bangumi/assets/63437036/1af69c6d-f774-4a0a-a7d1-2359b604c20b)
回复框上方工具栏（加粗，斜体，链接等）无法被点击选中，似乎是被回复框遮挡，点击时只会唤起输入法。
此问题在Android13/MIUI14上和Android8/EMUI8上都有出现，初步排除MIUI魔改的问题。但此问题在Win11子系统和模拟器上（Android13）没有出现，可以正常点击使用。
此问题最早出现在软件8.0.1版本上。
## 另外两件事
issue https://github.com/czy0729/Bangumi/issues/113 问题仍然存在，x86-64 apk可以安装但在运行时闪退，如果无法修复建议在release页面备注。
蓝奏云的apk链接在使用PC版浏览器的UA时仍可免费下载，所以可以继续保留……大概。

**Comment by czy0729** [comment]
我猜是虚拟按键的位置我没预料到？你帮忙试试用全面屏模式看看？

**Comment by Freddd13** [comment]
![Screenshot_2023-10-02-18-42-29-343_com.czy0729.bangumi.jpg](https://github.com/czy0729/Bangumi/assets/50367552/a44674d0-e2e9-4598-a043-9ac0f8ded674)

我xiaomi10s，android11/miui 12.5也这样好几个版本了… 我以为是已知等修状态（

**Comment by Manicsteiner** [comment]
> 我猜是虚拟按键的位置我没预料到？你帮忙试试用全面屏模式看看？

果然是系统导航栏虚拟按键的问题，Android13那台把虚拟按键改成全面屏手势就正常了。但是Android8这台改挡下边工具栏了。又试了一下，应该是可以在应用运行时隐藏导航栏造成的，先隐藏导航栏再启动应用就正常。
![Screenshot_20231002-184114](https://github.com/czy0729/Bangumi/assets/63437036/c5c6075d-6e18-4f90-b1df-8eb0cbbb033c)

**Comment by Freddd13** [comment]
换全面屏正常+1

Sent with a Spark
在 2023年10月2日 +0800 18:50，Manicsteiner ***@***.***>，写道：
