### ISSUE TITLE
无法正常输入文字

### ISSUE THREAD

**Issue by yujiangqaq** [czy0729/Bangumi#12]
在评论，评分，发短信等地的输入框输入文字时有较大概率发生光标乱跳，不管怎么点选都会跳到同一个位置，或者说光标“卡死”在一个位置上，不管因何原因（例如手动拖动光标，输入文字，输入BGM表情）改变了光标位置，都会在数秒内跳回去。

**Comment by yujiangqaq** [comment]
设备小米5s，小米平板4，MIUI10、11，均复现，bangumi客户端与输入法gboard均已升级至最新版

**Comment by czy0729** [comment]
4.4.2版本里面
- [x] [帖子] 留言输入框, 安卓暂时屏蔽控制光标的逻辑
以前都没问题, 安卓系统更新后操作光标就卡住, 所以我没再操作, 按道理应该不会有这个问题才对
现在我最怕就是我这里MIUI12没问题, 同样的写法变成其他不行了...

我手头还有台mi4 我这1 2个版本看看怎么修复

**Comment by czy0729** [comment]
现在不知道还有没有这个问题，还有的话可以继续留言
