### ISSUE TITLE
[bug]发现页自定义按钮区时自动退出编辑

### ISSUE THREAD

**Issue by Orzalpha** [czy0729/Bangumi#120]
https://github.com/czy0729/Bangumi/assets/74893333/2c1838ea-36d1-4415-9351-cfdee3548215

如上所示
系统版本：MIUI 14.0.11

**Comment by czy0729** [comment]
我觉得还是跟你之前告诉我的问题是一样的，就是在你的手机上面不知道什么原因导致了，我这边没复现到，也没碰到有其他人有类似问题。

**Comment by Orzalpha** [comment]
好的，我去排查下可能的原因

**Comment by czy0729** [comment]
不用关，我找到个跟你有类似情况的人了

**Comment by Orzalpha** [comment]
我有了一个猜测，我这边这个问题可能是由于“开屏跳过”应用导致的。
[开屏跳过](https://github.com/zfdang/Android-Touch-Helper)


https://github.com/czy0729/Bangumi/assets/74893333/6a39489d-c668-4f83-be38-1a8850ffd436



如上所示，关闭该应用的无障碍服务后不会出现此问题。
您可以尝试询问类似情况的用户是否也安装了这样的跳过广告软件。
之前没能发现是因为我使用小米一键换机把数据从旧设备换给了新设备，导致新设备即便没有安装该应用，但是它的服务可能也一起带了过来，并且无法去除。（有待验证，我会尝试恢复出厂设置后将设备手动恢复回来）
另：这个问题在 8.2.0 版本中似乎不会出现，可能是在新版本的改动导致触发了跳过广告软件的什么规则。如果您知道些什么，或者有什么猜测的话请告诉我，感谢。


https://github.com/czy0729/Bangumi/assets/74893333/79fab411-4c31-42c9-84df-532c9042b42c

**Comment by Orzalpha** [comment]
刚刚尝试将手机恢复出厂设置后直接安装 bangumi，没有问题。
之后重启手机，这个问题就出现了。

**Comment by Orzalpha** [comment]
提供另外的信息：我使用两台设备进行测试。
第一台：（MIUI14.0.11）
将手机恢复出厂设置后在不登录小米账号的情况下测试，直接安装bangumi并登录，不会出现此问题。
长按电源键重启手机，没有出现问题。
语音命令小爱同学“确认重启”，之后出现此问题。

第二台：（MIUI14.0.2）
将手机恢复出厂设置后在不登录小米账号的情况下测试，直接安装bangumi并登录，不会出现此问题。
长按电源键重启手机，没有出现问题。
登录小米账号并开启云同步，长按电源键重启手机，没有出现问题。
使用小爱同学语音命令重启，出现问题。

导致我开始怀疑和小爱同学有关，但是之后那之前演示的平板电脑（MIUI14.0.6）也试了下，关掉无障碍的时候并不会出现此问题。
但是实际上在第二台设备上之前关闭无障碍时出现过这个问题，导致我也拿不太准。
另：在某次第一台恢复出厂设置后，我开了手机分身，在分身空间里安装 bangumi，最开始也没有出现此问题，之后我重启设备（忘记重启方式了），再进分身发现分身也出现了这个问题了（主空间也安装了bangumi并且出现问题）。

不折腾了，以上是我能提供的信息。

**Comment by czy0729** [comment]
我会找我那个也是开发的朋友调通的，不用这么折腾，谢谢反馈

**Comment by czy0729** [comment]
https://github.com/software-mansion/react-native-gesture-handler/issues/2655
原来你测试到的无障碍确实是问题所在
