### ISSUE TITLE
[BUG] 时间胶囊的条目在翻页后是重复的

### ISSUE THREAD

**Issue by kahosan** [czy0729/Bangumi#122]
只有「全站」这个选项里的数据是重复的

**Comment by czy0729** [comment]
「全站」网页版也是只有第一页的。

为了不再迷惑，目前已经改成全站只显示一页数据。
https://github.com/czy0729/Bangumi/blob/21948bde9aebab0789b64ca951bac738e4fab8d5/src/stores/timeline/common.ts#L185

可以通过再次点击时间底栏「胶囊按钮」刷新到顶。
