### ISSUE TITLE
[Discuss]有考虑使用GitHub Actions打包ipa吗

### ISSUE THREAD

**Issue by capric98** [czy0729/Bangumi#128]
看到博客上说mac环境挂了，假如要重新折腾要不要考虑下用Actions？现在也有M1环境了

**Comment by czy0729** [comment]
因为种种原因，其实我并不能正常打包出 IPA，我是通过了很多其他手段去达成的。当然现在问题在更前，是用到的库的问题，所以跟 ACTIONS 没多大关系。

**Comment by czy0729** [comment]
https://github.com/czy0729/Bangumi/releases/tag/8.3.1
已传。
