### ISSUE TITLE
ui问题

### ISSUE THREAD

**Issue by QAQ2077** [czy0729/Bangumi#130]
![Screenshot_2023-12-23-19-49-22-93_462c1a9ead48ae2a875e978a4cce1a89](https://github.com/czy0729/Bangumi/assets/105648422/d6ccfef3-6002-4316-8293-007e16a90fd2)
![Screenshot_2023-12-23-19-49-32-56_462c1a9ead48ae2a875e978a4cce1a89](https://github.com/czy0729/Bangumi/assets/105648422/564563ba-52bc-4f11-9c2e-148589f14246)
![Screenshot_2023-12-23-19-50-41-08_462c1a9ead48ae2a875e978a4cce1a89](https://github.com/czy0729/Bangumi/assets/105648422/da8e0aa4-526f-4199-858c-2001931c7fa8)
就这些ui，或多或少都有问题，他本身设计就是这样的吗？

**Comment by czy0729** [comment]
不同机型没办法都测到，其实可能存在很久，只是没人提，我看看代码。

**Comment by QAQ2077** [comment]
一加 Ace 2 Pro 安卓13
我用的这个

**Comment by QAQ2077** [comment]
![Screenshot_2023-12-24-12-37-49-41_462c1a9ead48ae2a875e978a4cce1a89](https://github.com/czy0729/Bangumi/assets/105648422/4f9c007e-6035-4870-917e-4ce8a2938a48)
我想问一下，就是每日放送里面多少多少话？点开详情之后并和前面显示的不一样，也不知道是啥逻辑，也不知道这代表啥意思

**Comment by czy0729** [comment]
这个其实是更新到多少集，但是我最新代码里面已经移除了，实在没办法去维护这些一直在变化的数据

**Comment by QAQ2077** [comment]
呃，我想问下赞助后多久能获得那高级功能？
