### ISSUE TITLE
作品详情页收藏按钮UI

### ISSUE THREAD

**Issue by Risuntsy** [czy0729/Bangumi#131]
详情页的 `收藏` 按钮框，似乎在最上层，遮挡了 `目录` 和 `删除收藏` 两个按钮的大部分，想要点击按钮只能以一个很刁钻的位置 XD

![f21f4371a1edac18ecab4e094da05e9b](https://github.com/czy0729/Bangumi/assets/79560036/017a5307-e098-4333-b264-6397d5d20b00)

**Comment by czy0729** [comment]
最新代码已经修复好，但是我正常在做一些整体流畅度优化，可以等到下一个版本XD

**Comment by Risuntsy** [comment]
最新版本似乎还是有同样的情况XD，只有点击格子外面的那一点能点击到
![7A2DB00231A04667F7EF5878570B5591](https://github.com/user-attachments/assets/f2b0559a-80f0-4d3a-a91d-45f2d4fde1ad)

**Comment by czy0729** [comment]
可能react-native安卓渲染根本不看 z-index，很纯粹只看代码的是放前面还是后面，我把这个两个按钮的布局代码往下移估计好了XD。
