### ISSUE TITLE
[Bug] 收藏页进度展示问题

### ISSUE THREAD

**Issue by Orzalpha** [czy0729/Bangumi#134]
版本 8.4.2

![Screenshot_2024-01-09-15-23-06-714_com czy0729 bangumi](https://github.com/czy0729/Bangumi/assets/74893333/d09eb72b-8780-41c4-81d4-836a6857435e)

如上，我心危第二季放送数字展示应为 13/13/25，实际缺少一项，且进度条展示效果也不正确。

疑似是一个以前被修复过的 bug，见 [ISSUE121](https://github.com/czy0729/Bangumi/issues/121) 

感谢作者大大。

**Comment by czy0729** [comment]
https://github.com/czy0729/Bangumi/commit/05c8fda1afe0c257b4c1ea437eafb63210cd0d38
