### ISSUE TITLE
自定义源头上传云端一直失败

### ISSUE THREAD

**Issue by georgez1379** [czy0729/Bangumi#135]
精选了好几个第三方番剧，漫画网站作为跳转源，但数据上传不了。![Screenshot_2024-01-10-15-55-28-219_com.czy0729.bangumi.jpg](https://github.com/czy0729/Bangumi/assets/63297611/f95f3295-f146-4cf4-ba31-c3e1ca138e47)测试了不同网络，自定义源头还是一直提示上传中，赶紧修复下吧，不同设备中，数据不同步太难受了

**Comment by czy0729** [comment]
我今晚处理一下，打包后会直接放在这个issue里面先。

**Comment by georgez1379** [comment]
还是上传不了 什么时候修复呢

**Comment by czy0729** [comment]
夜点单独给你打个包，需要新打包

**Comment by czy0729** [comment]
https://www.123pan.com/s/K0fQjv-5CTVd.html

**Comment by georgez1379** [comment]
下载更新这个版本，上传下载都没问题了。辛苦作者君啦
