### ISSUE TITLE
[Bug] 8.4.4 版本，单击版本框检查更新时触发致命错误弹窗

### ISSUE THREAD

**Issue by icyphoenix98** [czy0729/Bangumi#137]
8.4.4版本，在设置菜单单击‘版本’，使用跳转检查更新功能时稳定触发致命错误弹窗
报错code：
Error: Fatal: ReferenceError Property 'open' doesn't exist
很抱歉，需要重新启动，若次错误稳定触发，恳请截取此屏幕并告知作者，谢谢！

重启后稳定触发。

![Screenshot_2024-01-18-15-54-22-997_com czy0729 bangumi](https://github.com/czy0729/Bangumi/assets/38468147/009d3451-6c71-41af-b7b4-5a3f85ed4f07)

**Comment by czy0729** [comment]
https://github.com/czy0729/Bangumi/commit/5793683a7d4f08fe7e52badb7e262ee0ed9a50ce#diff-a2b47effc71095ea3c47bdcaa30bdd29a46a0635722f16dea8b87947d35176cd
已修，需要等到下次打包发布！
