### ISSUE TITLE
[Bug] 番剧简介翻译后，顺序会倒过来

### ISSUE THREAD

**Issue by david082321** [czy0729/Bangumi#139]
![Screenshot_20240120_140852_Bangumi](https://github.com/czy0729/Bangumi/assets/7046617/1faaa62e-389d-44e6-bb30-8d30cc624a00)
![Screenshot_20240120_140902_Bangumi](https://github.com/czy0729/Bangumi/assets/7046617/56a0df86-c5f0-43d6-a67d-543ac00c2775)

**Comment by czy0729** [comment]
收到，谢谢反馈。
