### ISSUE TITLE
Feature request: 进度更新序排序

### ISSUE THREAD

**Issue by yyyy52** [czy0729/Bangumi#14]
希望进度中的动画能够增加按照最近更新的顺序排序的选项，以方便看完新番后标记。

**Comment by czy0729** [comment]
我记得网页排序不就是这个样子的吗

**Comment by yyyy52** [comment]
网页应该是按照添加进在看的顺序排序的

**Comment by czy0729** [comment]
其实我还是没懂你想要什么排序, 设置里面有APP和网页, 你要的那种跟这2个有什么区别呢, 具体点

**Comment by yyyy52** [comment]
app顺序应该是 今日放送->明日放松->...
我希望的是 今日已放送->昨日已放送->前日已放送->... 的感觉
感觉不是很要紧的需求我还是close了吧

**Comment by czy0729** [comment]
可以 我今天才放假 有实际了

**Comment by yyyy52** [comment]
感谢🙇

**Comment by czy0729** [comment]
已经更新上去了, 但是不知道是不是你想要的

**Comment by yyyy52** [comment]
明日放送在前面比我想要的还好。谢谢

**Comment by czy0729** [comment]
其实还是不够准 这个星期几 特别是那些刚好日本是今天 国内是明天的番
