### ISSUE TITLE
應用內更新

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#144]
請問能增加透過GitHub應用內更新嗎 每次更新都要跳轉老實說有點麻煩

**Comment by czy0729** [comment]
不打算做，最多也就加个按钮点一下看能不能从github下载，因为国内我敢说至少80%的用户github都打不开。

**Comment by NeKoOuO** [comment]
> 不打算做，最多也就加个按钮点一下看能不能从github下载，因为国内我敢说至少80%的用户github都打不开。

加個按鈕好啊😀

**Comment by ceynri** [comment]
哈哈哈，看到这个 issue 才发现我还在用一年前的版本

**Comment by NeKoOuO** [comment]
ghproxy.com 有這個應該就可以實現了吧

**Comment by NeKoOuO** [comment]
> 不打算做，最多也就加个按钮点一下看能不能从github下载，因为国内我敢说至少80%的用户github都打不开。

ghproxy.com

**Comment by czy0729** [comment]
> ghproxy.com

直接墙了

**Comment by NeKoOuO** [comment]
https://mirror.ghproxy.com/ 可以用鏡像
