### ISSUE TITLE
页面内的文字无法互动

### ISSUE THREAD

**Issue by LogicDX342** [czy0729/Bangumi#146]
目前在条目页面和小组帖子都遇到过，包括点击链接无法跳转，文字无法选中，甚至我来提issue时设置页面的那个github链接也点不开。有时也会出现帖子里主楼文字正常，但回复里的都无法选中的情况

**Comment by czy0729** [comment]
什么版本的客户端

**Comment by LogicDX342** [comment]
8.4.2，不过这个bug在6.x的时候就遇到了

**Comment by LogicDX342** [comment]
试了下8.6.0，还是有这个问题

**Comment by czy0729** [comment]
无法选中是我某个版本故意这么弄的，有某种无法解决的问题导致我那个时候这么做，现在忘记了可能会流畅很多，不过我现在再打开看看会如何。
