### ISSUE TITLE
里番“看到”功能失效

### ISSUE THREAD

**Issue by xinzhisuodong** [czy0729/Bangumi#148]
试了下表番那边可以但里番就失效了，以前还行的，原本我以为旧手机安卓9问题，现在换到另一台手机安卓11结果还是不行
https://github.com/czy0729/Bangumi/assets/162891518/26ff534f-b638-4310-b888-6bb2caf43d78

**Comment by czy0729** [comment]
里番失效多数是授权token失效了，试下重新登录。

**Comment by xinzhisuodong** [comment]
> 里番失效多数是授权token失效了，试下重新登录。

重登也不行，我用这款app“看到”功能能正常应该不会账号问题
![Screenshot_2024-03-31-02-08-45-748_com.miui.home.png](https://github.com/czy0729/Bangumi/assets/162891518/a2bd18f7-6958-4c71-94a4-980bc41bb1d6)

**Comment by czy0729** [comment]
确实，nsfw看到不行，应该是用了旧的官方api，那种api在nsfw已经全部不响应了，需要重新用新api写了。
