### ISSUE TITLE
启动闪退

### ISSUE THREAD

**Issue by Flyfish233** [czy0729/Bangumi#15]
java.lang.UnsupportedOperationException
at
android.webkit.WebviewFactory.getProvider(WebviewFactory.java:241)
at
android.webkit.Cookiemanager.getlnstance(Cookiemanager.java:40)
at
com.facebook.react.modules.networkForwardingCookieHandler.getCookieManager(ForwardingCookieHandler.java:3)
at
com.facebook.react.modules.networkForwardingCookieHandler.get(ForwardingCookieHandler.java:1)
at

**Comment by czy0729** [comment]
你这个是APP闪退 还是window开发环境闪退

**Comment by Flyfish233** [comment]
我使用了一个不带 Android Webview 的 armhf 设备，一次卡bug没弹出这个闪退界面，功能都正常。

**Comment by czy0729** [comment]
我终于知道你是在什么环境运行了，居然是那个小米手表？
进不去，怎么想都进不去吧
