### ISSUE TITLE
ios的Expo Go无法加载bgm

### ISSUE THREAD

**Issue by yyyy52** [czy0729/Bangumi#154]
![IMG_7033](https://github.com/czy0729/Bangumi/assets/53691794/8f9d5eee-c2d9-4e4b-bbc3-5b94dacfa64c)

**Comment by czy0729** [comment]
太操蛋了，调了一天
https://github.com/czy0729/Bangumi/commit/b91f8af941d41142f2f720681bab1b3fa423cc00
