### ISSUE TITLE
狀態顯示有誤

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#158]
https://github.com/czy0729/Bangumi/assets/111511925/45deeaa9-60b9-464a-84c3-326fe0c43e66

**Comment by czy0729** [comment]
其实设计就已经衡量过，因为这个列表本来就没状态，这些状态都是列队去官方API里面找的，这些接口网络请求其实相当慢。
如果本地没状态是都找，若之前有状态数据，会忽视掉搁置和抛弃，因为通常来说一旦设置成这两种状态是极少改变的，以达到减少请求数，就算不是这两种也有一个很大的请求间隔，不然会有请求风暴。
虽然多请求几次也无碍，但这是一个全局组件，几乎所有列表都有，性质就不一样了。你点进去还是会更新的，不太影响实际使用，并不打算改哈。
相反我是没测试出来在这些地方展开会有一个多余的动画跳动效果，和没有转繁体，这才是要改的。

**Comment by NeKoOuO** [comment]
了解
