### ISSUE TITLE
Opencc 

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#159]
目前用的香港轉換由於文本量太少很多轉換錯字 例如後面的面被轉成麪粉的面
我覺得轉換不如用台灣的會比較好 或者加個可以台灣香港切換的按鈕

**Comment by czy0729** [comment]
![image](https://github.com/czy0729/Bangumi/assets/13514316/51392ee0-9dab-4f74-9881-2234058c5b11)
https://github.com/czy0729/Bangumi/commit/baf7db76f4c14ae2223b8232822c6ab8c7bde695
