### ISSUE TITLE
卡住

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#160]
有時候正常用一用就會突然什麼都點不了 不是卡住 但就是什麼都點不了 滑動還是正常的 就點擊的功能用不了

**Comment by czy0729** [comment]
这个问题我是知道的，但是原因找不到，能想到的只有一个代码，我可以禁用后给你调试

**Comment by czy0729** [comment]
https://github.com/czy0729/Bangumi/releases/download/8.10.0/bangumi_v8.10.1_arm64-v8a_test.apk
这个是我注释了一个优化代码的编译，感觉注释掉后第一次进入新页面有比以往明显掉帧。
顺便把 deeplink 也重写了一下，不过我也不太懂，没有在浏览器的分享里面看见客户端，不清楚是否正常工作。

**Comment by NeKoOuO** [comment]
Okay 我試試看

**Comment by NeKoOuO** [comment]
目前一切正常 👏

**Comment by czy0729** [comment]
https://github.com/czy0729/Bangumi/commit/2e32ae5ab7c73ac800ed85759e983b4fbd49ac3a
