### ISSUE TITLE
顯示原文標題

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#162]
沒想到這個東西居然沒人提 現在只顯示中文名 卻沒有原文 導致想複製原文沒地方複製（詳情也沒有）
希望能夠在中文標題的下面一行顯示原文標題
![Screenshot_2024-05-29-17-08-18-075_com.czy0729.bangumi.jpg](https://github.com/czy0729/Bangumi/assets/111511925/9318b86c-cd02-4d95-89fc-14c3b9e190e3)

**Comment by czy0729** [comment]
后面打包那个其实就已经修回去了
