### ISSUE TITLE
中文名/日文名

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#165]
這個標準在哪 有些顯示原文有些顯示中文 還是這是BUG
![Screenshot_2024-05-31-19-32-50-109_com.czy0729.bangumi-edit.jpg](https://github.com/czy0729/Bangumi/assets/111511925/354fce38-e09a-4a5b-9142-a3978bd44fa4)

**Comment by czy0729** [comment]
设置里面开了中文优先，客户端有一份静态数据，找到了就显示

**Comment by NeKoOuO** [comment]
有這個我開了 你看芙莉蓮就知道

**Comment by NeKoOuO** [comment]
上面和右邊的我點進去 是有中文的 但是外面一樣沒有

**Comment by czy0729** [comment]
原始数据就这样，并没有中文，中文是在 `bangumi-data` 里面匹配到的
```
{
  cover: 'https://lain.bgm.tv/pic/cover/l/a1/bd/305429_axzF3.jpg',
  info: '4677人关注',
  subjectId: '305429',
  title: '葬送のフリーレン'
}
```
里面的数据并没去关联外面的，感觉也没什么必要，真做也不是不能做。
