### ISSUE TITLE
尷尬了最新版本還是卡了

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#167]
一樣只能滑動不能點擊

https://github.com/czy0729/Bangumi/assets/111511925/384382d1-5e7a-4ea6-babc-4f96033d709a

**Comment by czy0729** [comment]
只能先看看频率了，因为随机出现，目前是在路由层数5之后我才打开那个节省内存的方法，不过大概率就是这个玩意导致的。

**Comment by NeKoOuO** [comment]
今天又觸發一次了😭

**Comment by czy0729** [comment]
刚刚我又想了一下，也有可能是模态框销毁后，那个阻止触摸的层没完全销毁导致的，但是也是要验证。

**Comment by NeKoOuO** [comment]
目前都沒有遇到了
先close有遇到再open

**Comment by NeKoOuO** [comment]
又有了…
