### ISSUE TITLE
出现了这样的错误

### ISSUE THREAD

**Issue by LOVEMEBUT** [czy0729/Bangumi#17]
机型:k20pro 8+256 
安卓版本:10
miui版本:12.0.6稳定版
具体的看图片吧，谢谢开发出这么好用的应用。
![Screenshot_2021-03-23-22-21-16-904_com czy0729 bangumi](https://user-images.githubusercontent.com/20140506/112162271-ded3cb00-8c26-11eb-9fde-5fb37c7dcc9c.png)

**Comment by LOVEMEBUT** [comment]
在点击各话的单独吐槽时出现的问题

**Comment by czy0729** [comment]
没看懂怎么复现 你可以一步一步说给我看 点什么动漫 然后点什么按钮触发
