### ISSUE TITLE
 [Feature Request] 发现页向下翻动的同时 列做横向滚动

### ISSUE THREAD

**Issue by yyyy52** [czy0729/Bangumi#172]
![335560891-354fce38-e09a-4a5b-9142-a3978bd44fa4](https://github.com/czy0729/Bangumi/assets/53691794/358551ec-171f-4d7b-a6e4-7e2633c0e6f5)

**Comment by czy0729** [comment]
这需求太怪了，而且就算做也无法准确控制到什么时候该动。
