### ISSUE TITLE
增加日誌功能

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#177]
每次用一用就閃退 然後又不能看原因在哪好難受
![Screenshot_2024-06-26-03-26-44-229_com.czy0729.bangumi.jpg](https://github.com/czy0729/Bangumi/assets/111511925/e2a5dd3b-6018-4fd2-88dd-bca716e2eeeb)

**Comment by czy0729** [comment]
就是我也没找到办法，不然我早加了。
你可以说说这次是怎么触发的，其实整个应用都很网页，来来去去不外都那几个错误，绝大部分都是人为的。

**Comment by czy0729** [comment]
翻了一下自己的很简单的错误上报，全都是 TypeError undefined is not a function。
所以大概率是有地方接口没给值，直接用了就报错了，但是也是没办法简单定位到是哪，只能看什么步骤能稳定触发。

**Comment by NeKoOuO** [comment]
好 我試試

**Comment by czy0729** [comment]
有能稳定触发的记得反馈，只要能找出来哪怕一个，都能显著减少闪退。
