### ISSUE TITLE
更新條目資料

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#178]
時間跨度貌似有點久了
![Screenshot_2024-06-27-02-00-33-850_com.czy0729.bangumi.jpg](https://github.com/czy0729/Bangumi/assets/111511925/2beafa82-08e2-4d81-8202-6654c9f63077)

![Screenshot_2024-06-27-02-00-52-992_com.czy0729.bangumi.jpg](https://github.com/czy0729/Bangumi/assets/111511925/4f689834-8fc4-4301-bc1f-ebeff2271d59)

**Comment by czy0729** [comment]
这里几乎都是手工的，但是鉴于信息来源的网站要么变了要么没了，更新一次源数据工程量就很大，性价比特别低，我看看工作量。

**Comment by czy0729** [comment]
galgame数据重新抓了。
nsfw那边基本不可能续了，直接把功能重写了。

**Comment by NeKoOuO** [comment]
什麼意思阿 是需要重寫嗎

**Comment by czy0729** [comment]
就是功能已经用别的功能代替了，旧的那个还在保留，有一个新的代替了
