### ISSUE TITLE
拼图分享功能无法使用

### ISSUE THREAD

**Issue by hsiayuchih** [czy0729/Bangumi#179]
拼图分享生成后提示“长按分享”，但是长按后并没有任何反映，app相关的权限也全部已经给了

**Comment by czy0729** [comment]
MIUI我刚试了一遍是可以的，正常来说会问你要相册读写权限，没弹窗也有可能是拒绝过后再也不显示，如果都给了权限其实我也没什么办法判断是哪里出问题。

**Comment by czy0729** [comment]
可能国产系统就根本不看代码，所以我在测试的时候如果没影响，我就把那个权限在XML里面删掉了，我迟点把正常的写法加回去再试试。

**Comment by hsiayuchih** [comment]
> 可能国产系统就根本不看代码，所以我在测试的时候如果没影响，我就把那个权限在XML里面删掉了，我迟点把正常的写法加回去再试试。

大佬怎么关闭了，加进去也不行嘛

**Comment by czy0729** [comment]
感觉会错意了，你说的分享是分享到别的应用，还是把图片下载到本地？分享是做不了的。
