### ISSUE TITLE
即使重啟仍舊顯示舊的快取

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#180]
https://github.com/user-attachments/assets/5d56e889-81fa-43c3-b379-7504d06f1556

**Comment by czy0729** [comment]
视频看完了，其实你想什么数据是变化的，我貌似是写了一个几个小时的间隔。

**Comment by NeKoOuO** [comment]
> 视频看完了，其实你想什么数据是变化的，我貌似是写了一个几个小时的间隔。

這個頁面全是4月的 現在已經7月了

**Comment by czy0729** [comment]
其实是每个季度的新番那个时间整理都会卡到播放前几天才知道，其实已经更新完了，只是我还没发版本，而且我没弄在线更新数据。
https://github.com/czy0729/Bangumi/commit/b22f468e1d56881f3ea22ff89555f8272a2aaaa2
不过按道理放完的条目应该会自动消失才对，我看看。

**Comment by NeKoOuO** [comment]
正常應該要長這樣![Screenshot_2024-07-15-19-56-33-883_com.czy0729.bangumi.jpg](https://github.com/user-attachments/assets/95f4b703-bd18-4f28-86de-65bf0c85384a)
