### ISSUE TITLE
需要更新 Expo 的 bgm 版本

### ISSUE THREAD

**Issue by dyphire** [czy0729/Bangumi#182]
Expo 上的 bangumi 好久没更新了，停在 8.9.0 了
![IMG_4292](https://github.com/user-attachments/assets/fc8c3efe-1933-44f4-8d40-1c0120817c85)
而且几个月前 expo 商店版更新就把 SDK 最低版本提到了 50，bgm 还是 49，一直都没敢更新 Expo

**Comment by czy0729** [comment]
大可放心更新，看来是Expo把不符合的版本给过滤了，实际上每个版本我早就上传了。现在Expo已经很鸡贼，只维护最新版本。
