### ISSUE TITLE
增加自動加載圖片功能

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#183]
每個圖片要看之前都要點一次有點難受
![Screenshot_2024-07-24-20-15-38-836_com.czy0729.bangumi-edit.jpg](https://github.com/user-attachments/assets/3c9f2418-b712-45f1-a77e-1fb99e42f105)

**Comment by czy0729** [comment]
其实就是用户用图床根本不考虑其他看的人，所以我才坚决不做自动加载的。
他们首先不考虑别人能不能访问，其次也不看图片大小，再而帖子不能控制有多少图片，所以很有可能变成流量小偷。
当然无条件加载放开一个设置也不是不行。

**Comment by NeKoOuO** [comment]
> 其实就是用户用图床根本不考虑其他看的人，所以我才坚决不做自动加载的。
> 他们首先不考虑别人能不能访问，其次也不看图片大小，再而帖子不能控制有多少图片，所以很有可能变成流量小偷。
> 当然无条件加载放开一个设置也不是不行。

沒事我不怕😊

**Comment by czy0729** [comment]
其实现在超展开设置里面已经有一个设置是：小于2M自动加载，就像上面这个图片，这个图床连图片的大小都获取不了，放开的话完全不可控。

**Comment by NeKoOuO** [comment]
> 其实现在超展开设置里面已经有一个设置是：小于2M自动加载，就像上面这个图片，这个图床连图片的大小都获取不了，放开的话完全不可控。

不過那是給使用者選擇的阿 默認關就好了吧
