### ISSUE TITLE
留言區篩選貼貼會出現滑動卡頓

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#185]
全部和好友都不會出現卡頓

https://github.com/user-attachments/assets/8d25d52d-ce48-4729-899a-019a5367462a

**Comment by czy0729** [comment]
看了下其实是正常的，也没什么优化的空间。
帖子有一个逻辑是太多楼就会使用分页到底才加载更多，正常一页就十楼。
刚好开了贴贴这个楼层数过滤后没到那个逻辑，一次性全显示几十楼，就肯定就会有掉帧。
