### ISSUE TITLE
某些情況會導致上面的元素消失

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#186]
![Screenshot_2024-08-19-15-31-01-713_com.czy0729.bangumi.jpg](https://github.com/user-attachments/assets/3eb07539-cce2-4e0c-b58f-66cc30eb39c0)

**Comment by czy0729** [comment]
我也遇到过，貌似是重新授权的时候触发我，我检查下。

**Comment by czy0729** [comment]
最新代码下貌似无法复现，先搁置了。
