### ISSUE TITLE
今日上映总是慢一个季度，蛮奇怪的

### ISSUE THREAD

**Issue by TCOTC** [czy0729/Bangumi#187]
上个季度就是慢一个季度，这个季度也是

![Screenshot_2024-08-23-02-31-52-46_462c1a9ead48ae2a875e978a4cce1a89.jpg](https://github.com/user-attachments/assets/d697b5f5-2746-4fe6-986f-f8d1127e2a4f)

**Comment by czy0729** [comment]
这是不是最新版本的，实际上基本最慢一个星期我就全更新好了。
试下设置清一次缓存数据。

**Comment by TCOTC** [comment]
> 设置清一次缓存数据

这样确实正常了。不过这里是不是应该自动刷新一下？

**Comment by czy0729** [comment]
感觉很难复现，暂时我写个下拉逻辑强制发页面请求试试。
