### ISSUE TITLE
章节按钮的一点问题

### ISSUE THREAD

**Issue by TCOTC** [czy0729/Bangumi#189]
这种情况下是不是没法显示第22集？

![Screenshot_2024-08-23-03-39-27-99_462c1a9ead48ae2a875e978a4cce1a89.jpg](https://github.com/user-attachments/assets/e986d361-c9a0-4725-b504-e794a55f96fd)

**Comment by NeKoOuO** [comment]
你需要點第一集才會顯示

**Comment by czy0729** [comment]
我模拟一下这个情况，好久没碰这些逻辑，当初设计是会看见的。

**Comment by czy0729** [comment]
改了是有问题，问题是网格布局最大多少个章节按钮，直接用了列表布局的那个数目。

![image](https://github.com/user-attachments/assets/c4efdf97-be3a-4883-9dc3-445003bdf262)

关闭是这样
![image](https://github.com/user-attachments/assets/a3cbb87b-a2a5-47b1-aba6-5097d0064916)

开启是这样
![image](https://github.com/user-attachments/assets/005bfd00-00ae-46c6-bf48-19ea06621f60)
