### ISSUE TITLE
关闭CDN加速后，「发现」页面大图分辨率低

### ISSUE THREAD

**Issue by QQQQQH** [czy0729/Bangumi#19]
- 安卓
- 版本：4.9.3
- 下载渠道：Google Play Store
- 问题描述：如题，如下图
![Screenshot_20210404-095836](https://user-images.githubusercontent.com/48670154/113496525-19920900-952d-11eb-85b0-9d4c35bb97c9.jpg)

**Comment by czy0729** [comment]
发现页的数据我是通过CDN改过的，所以写代码的时候只兼容了CDN，这数据本来的来源图片就是这么个清晰度的
CDN能不关就不要关，其实为什么要关掉，是不是开了遇到其他的问题？

理论上这块我也可能做兼容，只是继续通过CDN，但是这样就直接绕开设置了

**Comment by QQQQQH** [comment]
> CDN能不关就不要关，其实为什么要关掉，是不是开了遇到其他的问题？

1. 看到好友的头像显示的是旧头像，而新头像似乎已经更换超过一周了；
2. 由于CDN的数据新鲜度的问题，「发现」页面的封面可能也会和条目页面不相同（如附件视频中的ホリミヤ）;
3. 另外在新一季度动画刚开播的时候（比如最近），同样由于CDN的数据新鲜度的问题，在「发现」页面中不会显示刚开播的动画。

而自己由于一直有使用网络代理，直接通过浏览器访问bangumi也不会觉得慢，于是就关闭CDN尝试了一下，这才发现关闭CDN后图片分辨率低的问题。

> 这数据本来的来源图片就是这么个清晰度的

这里是指关闭CDN后，bangumi官方API对应的图片分辨率就很低吗？条目页面内可以获取到高清晰度的封面，这两处的图片来源是不同的吗？

另外还有一件事情比较好奇，在开启CDN的情况下，条目页面左上角显示的封面，除了上述的「ホリミヤ」这种情况会替换封面之外，我发现点击进入「ワンダーエッグ」条目后，封面也很快被替换了，但是替换后的分明似乎不如替换前的清晰，详见附件视频（可能录屏经过压缩后看得不是很清楚，不过我觉得这应该是可以复现的）。

（不过似乎这些都不是什么大问题）

https://user-images.githubusercontent.com/48670154/113499394-4869a880-9548-11eb-8ce7-a41d6cb574c9.mp4

**Comment by czy0729** [comment]
> 看到好友的头像显示的是旧头像，而新头像似乎已经更换超过一周了；
这是纯粹就是我最近变懒了, 没刷新CDN而已, 这个版本刷一下

> 由于CDN的数据新鲜度的问题
> 替换封面之外，我发现点击进入「ワンダーエッグ」条目后，封面也很快被替换了
毕竟是快照, 通常写法也就只会以第一次的数据为准, 后面通常最多自己再手动刷新一次, 无奈现在能编辑wiki的人变多了, 最近我一直发现, 有很多人老是再替换封面, 甚至替换后其实都同一个封面, 导致地址变了, 而内容还是一样, 导致我CDN计算hash地址失效

> 封面也很快被替换了，但是替换后的分明似乎不如替换前的清晰
因为这个发现的封面是我自己单独维护的, 是800px宽, 其他正常的是480px宽, 而我通常的写法是会把缓存的地址都带过去跨页面做占位, 导致了这个800px的替换成480px的, 产生了这么一个奇怪的情况
只要是经过CDN的, 都是我本地处理过的, 保证了比网站正常/c/(cover)的清晰, 而没使用/l/(large)的原图, 那个不可控而且大浪费流量

其实这些问题我都是知道的, 感觉问题不大, 想处理也需要很多心思, 就一直没管, 毕竟这些问题其实1年到2年前就存在的, 也没人提嘛(bgm38)

**Comment by QQQQQH** [comment]
原来如此，那意思是CDN的图片都是通过官网/l/的图片处理后得到的是吗？

**Comment by czy0729** [comment]
是的, 官网的I图是我是不可能让他直接显示的, 每个人上传都不守一个规则, 有一些图大得7 8 M一张, 所以都是后处理过的

**Comment by QQQQQH** [comment]
明白了，感谢解答~
那我就先关闭这个issue了。
