### ISSUE TITLE
嵌套的 BBCode 显示有问题

### ISSUE THREAD

**Issue by LogicDX342** [czy0729/Bangumi#190]
比如[这个帖子](https://bangumi-app.5t5.top/iframe.html?id=screens-topic--topic&viewMode=story&topicId=subject/31737)，带链接的图片没显示出来

版本 8.12.4

**Comment by czy0729** [comment]
代码我几年前就过滤了，安卓几乎无解，react-native 中文本节点包裹其他非文本节点，直接全局崩溃。
https://github.com/czy0729/Bangumi/blob/80c7e892c6be26ddb394af84fc35bd6232db4046/src/components/render-html/a/utils.tsx#L24
