### ISSUE TITLE
剧照匹配错误

### ISSUE THREAD

**Issue by Elletear** [czy0729/Bangumi#192]
咕咕子看下这个条目的剧照匹配呢，本来第二部出来时就想说了，结果忘了。😂
PS：顺便问下是通过什么方式适配剧照的呢？
![S40908-16030463.png](https://github.com/user-attachments/assets/8e5d6c58-8ba5-4030-82c4-2cc3fe52e038)

**Comment by czy0729** [comment]
豆瓣，异端结果多针对优化匹配逻辑就会无限准确XD

**Comment by czy0729** [comment]
![image](https://github.com/user-attachments/assets/2c05678e-c915-4aa7-a964-176030b45f03)

**Comment by Elletear** [comment]
![S40914-19210040.png](https://github.com/user-attachments/assets/1a748f37-ee76-42c3-a7a5-062445e862f8)
@czy0729 
偶然发现上次说的问题并未修复完全，开始看着图片正常，往下滑一些之后？！😂

**Comment by czy0729** [comment]
实际上这个修复都没有在版本发布里面
