### ISSUE TITLE
关于“找条目”中的漫画

### ISSUE THREAD

**Issue by yuduotianguang** [czy0729/Bangumi#194]
找条目里的漫画在上次更新之后就出现了大部分漫画时间对不上，比方说2022年按评分人数排名，第二部漫画是亚人，但是亚人早在21年就完结了，第四部漫画弥留之国的爱丽丝更是16年完结的，由于是大部分漫画都出现了这样的情况所以希望您可以改进一下

**Comment by czy0729** [comment]
OK，我有空批量刷新下数据

**Comment by czy0729** [comment]
![a6771cd32d0f36cb61ec8c6cb67a3668](https://github.com/user-attachments/assets/bdacae8b-3869-427d-9470-80a68c5ffb8e)
![8c709847c997ce96afc1577a916d0b1a_720](https://github.com/user-attachments/assets/cab6db6f-10db-4097-8f20-c55364bc1061)

**Comment by czy0729** [comment]
![dab407e676802cccafdc0cf7eceda6b3](https://github.com/user-attachments/assets/2205b569-dea2-4c4f-a125-12d44bec0744)
![8d73abcc6d14c6da150d85e9fb948b98_720](https://github.com/user-attachments/assets/67f353d5-a39d-48e9-9859-2c8b674435e8)
