### ISSUE TITLE
条目信息栏排版问题

### ISSUE THREAD

**Issue by HanaHye** [czy0729/Bangumi#198]
网站近期对条目infobox的更新导致APP的对应部分出现排版问题，例如：
[博麗霊夢](https://bangumi-app.5t5.top/iframe.html?id=screens-mono--mono&viewMode=story&monoId=character%2F485)
[負けヒロインが多すぎる！](https://bangumi-app.5t5.top/iframe.html?id=screens-subject--subject&viewMode=story&subjectId=343241)
![image](https://github.com/user-attachments/assets/7e163b79-4572-464c-b421-886f0b4fc318)

**Comment by czy0729** [comment]
说实话没什么办法处理，你也不知道他明天会变成什么样子，要优化也不能在文字上面动手，只能在特定的 html 元素。

**Comment by czy0729** [comment]
![fa9f14bd00c66fa880d25400901a76d0](https://github.com/user-attachments/assets/7e91d5b4-7f4d-43f4-9e74-093ab8b9ec65)
![cf53b00c5edfdc87f6da1929d52fb810_720](https://github.com/user-attachments/assets/dc2e65fb-907c-416b-ba73-8d568a0f0892)
