### ISSUE TITLE
小圣杯中资金日志页点进去就白屏

### ISSUE THREAD

**Issue by azuse** [czy0729/Bangumi#2]
3.0开始出现此问题，3.01依旧没有解决，已尝试过重装
小米8，安卓10
![Screenrecorder-2020-04-01-23-06-19-418 mp4_20200401_231039](https://user-images.githubusercontent.com/22174280/78153842-15409500-746e-11ea-84ae-0cc50b5c99c5.gif)

**Comment by czy0729** [comment]
我估计参加失败的ICO, 已复现, 下版本修好, 清明前
