### ISSUE TITLE
「收藏」页面中「吐槽」特殊字符无法正常显示

### ISSUE THREAD

**Issue by QQQQQH** [czy0729/Bangumi#20]
- 安卓
- 版本：4.9.3
- 下载渠道：Google Play Store
- 问题描述：如题，无法正常显示字符「&」，如下图1。在条目的评价页面则可以正常显示，如下图2。

图1：
![Screenshot_20210404-112943](https://user-images.githubusercontent.com/48670154/113497771-90cd9a00-9539-11eb-8781-c1b414ef85e4.jpg)

图2：
![Screenshot_20210404-112914](https://user-images.githubusercontent.com/48670154/113497769-8f03d680-9539-11eb-9991-f66d1e2415cb.jpg)

**Comment by czy0729** [comment]
了解

**Comment by QQQQQH** [comment]
「发现」页面也存在相同的问题，原文标题为「ゴジラS.P<シンギュラポイント>」

![Screenshot_20210404-142119](https://user-images.githubusercontent.com/48670154/113500518-2b85a300-9551-11eb-9e1a-35feafe72e35.jpg)
