### ISSUE TITLE
8.16 IPA包

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#204]

**Comment by czy0729** [comment]
你也用上iphone了？等两天，有几个bug要重点处理。

**Comment by NeKoOuO** [comment]
沒問題😋，btw我發現iOS好像比android 更穩定

**Comment by czy0729** [comment]
已经打包放上来了。有个问题死活修补好，黑暗模式的话不影响使用，不能因为这个修不了就一直不发布。
