### ISSUE TITLE
源头功能

### ISSUE THREAD

**Issue by Nine499** [czy0729/Bangumi#208]
![Screenshot_2024-11-03-22-23-27-174_com.czy0729.bangumi.jpg](https://github.com/user-attachments/assets/74ab5966-f96d-494f-90c3-9504352e8e00)

![Screenshot_2024-11-03-22-23-45-907_com.czy0729.bangumi.jpg](https://github.com/user-attachments/assets/9a3a275f-0ce8-415f-b9cd-5bc68ec376a3)

我明明把哔哩哔哩关掉了，为什么源头还是有哔哩哔哩？

**Comment by czy0729** [comment]
我得加个设置，默认不开启正版播放源，这个是合并进去的，跟你的设置没关系。

**Comment by Nine499** [comment]
> 我得加个设置，默认不开启正版播放源，这个是合并进去的，跟你的设置没关系。

别有正版渠道了，没意义

**Comment by NeKoOuO** [comment]
> > 我得加个设置，默认不开启正版播放源，这个是合并进去的，跟你的设置没关系。
> 
> 别有正版渠道了，没意义

確實沒意義 要放正版還不如放巴哈

**Comment by Nine499** [comment]
![Screenshot_2024-11-06-13-15-05-515_com.czy0729.bangumi.jpg](https://github.com/user-attachments/assets/fa7351d8-b5c2-49b1-82bc-d911af0b227a)

这里没改啊，个人建议彻底删除正版播放功能

**Comment by czy0729** [comment]
> ![Screenshot_2024-11-06-13-15-05-515_com.czy0729.bangumi.jpg](https://private-user-images.githubusercontent.com/14026156/383416059-fa7351d8-b5c2-49b1-82bc-d911af0b227a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4NzA2NjUsIm5iZiI6MTczMDg3MDM2NSwicGF0aCI6Ii8xNDAyNjE1Ni8zODM0MTYwNTktZmE3MzUxZDgtYjVjMi00OWIxLTgyYmMtZDkxMWFmMGIyMjdhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA1MTkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljYmI0OGU2N2FmMDE5ODkxZjEyMjk1NTRiNjA0NmIzM2IxMWM2ODNhZDU5MTc1MjE0MDJlOTM4MGQ1NmVkMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.-qzNfc8m7xZuZL1egXCUyQ4TAsffY4uftSSMYNO0j6w)
> 
> 这里没改啊，个人建议彻底删除正版播放功能

这里纯粹改漏了，你不用不代表没人用啊，我自己最近才用过，比如“破刃之剑”我都懒得找清晰的，尤其配合在网页版直接点一下过去B站看了。
