### ISSUE TITLE
默認原畫與第二原畫收起

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#209]
每次展開詳情都被這個洗版 我希望能夠默認只顯示幾行剩下的點擊展開
![Screenshot_2024-11-06-11-13-58-490_com.czy0729.bangumi.jpg](https://github.com/user-attachments/assets/77e024aa-49b2-4602-8256-37a48c12ef84)

**Comment by czy0729** [comment]
这个地方按道理一直都是折叠的，如果自动会展开，证明代码在你的机型里面有问题。
但是我的手机没碰到过，在网页环境下碰到过。
这个地方有想过用新页面显示，因为就算在当前页面显示完，感觉也不好，以前可没这么多内容。

**Comment by NeKoOuO** [comment]
> 这个地方按道理一直都是折叠的，如果自动会展开，证明代码在你的机型里面有问题。
> 
> 但是我的手机没碰到过，在网页环境下碰到过。
> 
> 这个地方有想过用新页面显示，因为就算在当前页面显示完，感觉也不好，以前可没这么多内容。

他是原本就是全部默認收起，你點展開他是全部一起展開，然後我是希望能在第二層再有一個可點展開

**Comment by czy0729** [comment]
我也拿捏不住再展开到哪里啊，真不如安安心心改前进到新页面展示。
