### ISSUE TITLE
单集讨论错误

### ISSUE THREAD

**Issue by YXL76** [czy0729/Bangumi#21]
打开薇薇 -萤石眼之歌-ep4的单集讨论出现错误![IMG_20210420_002548.jpg](https://user-images.githubusercontent.com/43405544/115270661-2179bc00-a16f-11eb-9e46-e248a84b0b68.jpg)

**Comment by czy0729** [comment]
了解, 会使用这个复现来修复这种飘忽不定的渲染HTML的问题
