### ISSUE TITLE
NSFW封面進入詳情頁面無法顯示

### ISSUE THREAD

**Issue by NeKoOuO** [czy0729/Bangumi#214]
一般的封面沒問題

https://github.com/user-attachments/assets/44deebd9-e960-44f0-bbf1-90b51624ceb1

**Comment by czy0729** [comment]
可能是登录掉了，NSFW条目是额外请求另一个接口的，没授权信息那接口直接啥都不返回。虽然可以用外面的图做占位。

**Comment by NeKoOuO** [comment]
這讓我想到 mihon 的 bgm tracker 也是遇到NSFW不返回 真的很頭痛 不知道怎麼解決

**Comment by czy0729** [comment]
![ee3bdcb4d549f5f04c68b8579c680404_720](https://github.com/user-attachments/assets/f9b91700-2a86-47d3-a156-b3b3649846f4)
![69cee9d48db404c327636037696cf35e_720](https://github.com/user-attachments/assets/2b63a57e-8fce-473d-a338-c75d38502f69)

nsfw 打印出来的 cover 就是空的，直接用跳转的时候带过来的占位数据好了。

**Comment by NeKoOuO** [comment]
New release?👀
