### ISSUE TITLE
希望帖子里的图片能在软件里面加载

### ISSUE THREAD

**Issue by Dome-World** [czy0729/Bangumi#218]
目前跳转到浏览器有些割裂，建议直接在软件里显示出来><

**Comment by czy0729** [comment]
超展开设置里面是有的找找看。
因为用户贴的图片访问性参差不齐，并没有浏览器那样自动帮忙处理了很多问题，不敢随便无条件加载，会卡死客户端。

**Comment by Dome-World** [comment]
> 超展开设置里面是有的找找看。
> 因为用户贴的图片访问性参差不齐，并没有浏览器那样自动帮忙处理了很多问题，不敢随便无条件加载，会卡死客户端。

找到了，谢谢，不过我记得过去好像是点击在帖子里直接展示的。。。
