### ISSUE TITLE
按标签搜索的优化建议

### ISSUE THREAD

**Issue by Freddd13** [czy0729/Bangumi#23]
看到里面有个标签搜索的功能，但实际上这个搜索结果把只要包含相应标签的动画，哪怕只有很少的那种标签都包含进去了？这样的话感觉根本找不到想要的动画… 比如我搜治愈这个标签，然后再按排名排个序，结果竟然和直接去看排行榜没有很大差别了…

过少的标签个人感觉没法体现出动画的特点，能否添加一个只显示相应标签数大于多少的动画的功能，挺需要的。

**Comment by czy0729** [comment]
很遗憾告诉, 你要明白我是一个第三方应用, 第一方就是指这个网站其实跟我没任何关系
他这个逻辑不合理其实大家都知道, 所以标签几乎都是知道没啥用的, 没办法去实现这个建议

所以我后来才开发了比如那些找番剧这样的功能, 里面也有标签, 但是数据肯定不全, 当然想做还是可能的, 需要事先把全盘的数据都拿到的, 不太科学

**Comment by Freddd13** [comment]
> 很遗憾告诉, 你要明白我是一个第三方应用, 第一方就是指这个网站其实跟我没任何关系
> 
> 他这个逻辑不合理其实大家都知道, 所以标签几乎都是知道没啥用的, 没办法去实现这个建议
> 
> 
> 
> 所以我后来才开发了比如那些找番剧这样的功能, 里面也有标签, 但是数据肯定不全, 当然想做还是可能的, 需要事先把全盘的数据都拿到的, 不太科学

😭
