### ISSUE TITLE
请求在 Google play 与 github releases 中添加其他架构版本

### ISSUE THREAD

**Issue by txyyh** [czy0729/Bangumi#24]
如题
这样老机和虚拟机也能在play上更新了

**Comment by czy0729** [comment]
github releases的蓝奏云其实就是全版本的
Google play可以加, 我还没玩熟

**Comment by txyyh** [comment]
那releases里面那个安装包大小16M是什么情况喵

**Comment by czy0729** [comment]
以前一直都是16m, 新的手机基本都能用16m, 是64位
30多m的是全版本兼容

**Comment by txyyh** [comment]
清楚
那就等我armv7破机在play里加载出bangumi了

**Comment by txyyh** [comment]
（我来催了

**Comment by czy0729** [comment]
google play那个后台我操作不懂啊, 我试过添加过2个包, 后面又出现一堆问题, 而且弄2个包我现在是怕影响到所有人, 能不能不要纠结这个在google play下载呢. 其实universal我都已经单独传到github的release里面了, (bgm38)

**Comment by txyyh** [comment]
> google play那个后台我操作不懂啊, 我试过添加过2个包, 后面又出现一堆问题, 而且弄2个包我现在是怕影响到所有人, 能不能不要纠结这个在google play下载呢. 其实universal我都已经单独传到github的release里面了, (bgm38)

我是GitHub watch掉了，所以也能及时更新
（我觉得这个权当学习，以后做其他Android应用开发都会遇到啊

**Comment by txyyh** [comment]
https://developer.android.com/google/play/publishing/multiple-apks?hl=zh-cn
谷歌那找来的文章（可供参考
我也不是开发者，只是了解apks的机制而已

**Comment by czy0729** [comment]
![image](https://user-images.githubusercontent.com/13514316/130308274-7e7c5b8f-16f2-464f-ad8d-e3ad23d70d36.png)
v5.1.0在审核, 上传完才发现, v7a和universal的版本号都比之前所有发布过的都低, 理论上假如判断到不下载v8a的人都要卸载重新下(bgm38)

**Comment by txyyh** [comment]
您close的太快了。。。
![Screenshot_20210821105908](https://user-images.githubusercontent.com/41893946/130323344-2bb96e5e-69a2-4615-a326-eac82eda55f3.png)

**Comment by czy0729** [comment]
我自己测一下 头大了

**Comment by czy0729** [comment]
你这个图不兼容是点击更新后才显示 还是进入页面就显示了?
遇到这个情况能不能通过卸载重装的方式安装?

**Comment by txyyh** [comment]
本来就已经卸载了。。。

**Comment by czy0729** [comment]
怎么那么奇怪, 我这就传了3个包上去, 覆盖面积比之前还大10000个安装设备

**Comment by czy0729** [comment]
会不会是ABI问题, 几个月之前都是28, 最近只允许上传29了, 再过几个月只能上30了, 我编译前就把ABI改大了1

**Comment by txyyh** [comment]
三个包。。。
话说 universal 要传的吗？
我记得不应该匹配 v8 下 v8 ，匹配 v7 下 v7 ，那还需要universal。。

**Comment by czy0729** [comment]
这3个都丢上去了, 我小米10卸载了去商店看, 显示是12M的大小, 那明显是匹配中了v8或者v7, universal是28m

**Comment by czy0729** [comment]
你这手机是主力机吗, 看看系统版本是多少

**Comment by txyyh** [comment]
8天前沦为备用机。。。
系统是类原生A11，DRM L3，通过 safetynet 认证
![Screenshot_20210822-121255832](https://user-images.githubusercontent.com/41893946/130341939-f43ff98a-42bf-41dd-9ba4-51d17439b325.jpg)

**Comment by czy0729** [comment]
其实我现在最关心的问题是 是不是所有人都坏了 （bgm38）

**Comment by txyyh** [comment]
那没有（
主机v8刚正常下载

**Comment by czy0729** [comment]
https://github.com/czy0729/Bangumi/blob/532e33756327ce55d9ba22ec5b52f2a0f9ab6a20/android/app/build.gradle#L204

这后面还有2个没编译的， 你那个机不会是这个吧

**Comment by txyyh** [comment]
那没。。。
骁龙800 armv7
