### ISSUE TITLE
特定帖子进入后闪退

### ISSUE THREAD

**Issue by NeutronStarT** [czy0729/Bangumi#25]
手机分辨率：2400*1080
系统：MIUI 12.5.2（安卓11）

打开这个帖子后出现了闪退
![IMG_20210817_232112](https://user-images.githubusercontent.com/31755002/129755685-55bd57c9-bc9d-4051-a4a6-ba9e2088150b.jpg)

![IMG_20210817_232239](https://user-images.githubusercontent.com/31755002/129755697-960ada3c-e639-4965-a6f4-c80b37baa76b.jpg)

**Comment by czy0729** [comment]
收到，这种帖子闪退，其实就是有部分代码写法没能识别到，被当做了文字渲染，然而RN这个框架只要文字渲染不包裹Text组件就直接死掉没商量，连try catch都没办法
所以只要碰到一个就处理一个，很快就很难再会有闪退情况了
