### ISSUE TITLE
希望应用能适配横屏

### ISSUE THREAD

**Issue by Snapmali** [czy0729/Bangumi#26]
个人经常拿平板看动画，想要记录的时候就需要拿手机打开应用进行记录，用平板的话就只能竖屏，不是很方便。
实际上我开启了强制横屏简单测试了一下，条目详情页显示效果还不错，仅有首页大卡片比例有问题，以及进度和时光机条目略宽，时光机banner略大。如果能对这些稍作调整，个人认为允许应用横屏问题不大。

**Comment by 850710247liu** [comment]
+1 
最近买了matepad11，在平板上无法横屏使用起来确实很费劲，希望作者大大有时间能实现一下QVQ

**Comment by czy0729** [comment]
> +1 最近买了matepad11，在平板上无法横屏使用起来确实很费劲，希望作者大大有时间能实现一下QVQ

真的是打算推进的，但是切屏的时候，怎么更新布局是个大问题，肯定不能一时间写好，特麻烦，bgm38

**Comment by 850710247liu** [comment]
> > +1 最近买了matepad11，在平板上无法横屏使用起来确实很费劲，希望作者大大有时间能实现一下QVQ
> 
> 真的是打算推进的，但是切屏的时候，怎么更新布局是个大问题，肯定不能一时间写好，特麻烦，bgm38

做成平行视界模式怎么样？内部代码都不用变，而且横竖屏切换也很快。

**Comment by 850710247liu** [comment]
这种双界面的平行视界模式
![IMG_20211128_123605.jpg](https://user-images.githubusercontent.com/59795360/143729782-1a5e92dc-6bee-43b9-a2da-b4473af98bc4.jpg)![IMG_20211128_123526.jpg](https://user-images.githubusercontent.com/59795360/143729784-099690d2-60b3-4f64-8c08-aaf49394d309.jpg)

**Comment by 850710247liu** [comment]
https://blog.csdn.net/weixin_44708240/article/details/105527775

你使用华为或者小米的分屏框架，代码不用动，就能实现平行视界。

**Comment by czy0729** [comment]
> https://blog.csdn.net/weixin_44708240/article/details/105527775
> 
> 你可以使用华为或者小米的开源分屏框架，代码不用动，就能实现平行视界。
> 
> 历时在软件左面点弹出的新页面将会显示在右面，方便了使用，而且也能快速横竖屏切换。

这些黑科技对于我这种非原生应用来说基本没办法支持，目前个人能力只能在最直接最蠢的地方去尽量适配。
