### ISSUE TITLE
话说我为啥成了会员 = =， 是bug吗

### ISSUE THREAD

**Issue by Freddd13** [czy0729/Bangumi#27]
印象里没投过食呀，刚一看我显示是会员233。。。我挺喜欢这个app的，发现它以来就一直用着，现在读研没空看番的时候也能刷刷bangumi，比起bgmtv网站它更适合我这种没啥时间的人 。所以想了想，第一次给开源作者💰了一波，希望能长期维护下去~

**Comment by czy0729** [comment]
应该是我看帖子的时候，看见有人安利app，所以我就直接拉一个所谓会员了，结果居然也掐到了饭，b38
