### ISSUE TITLE
macOS Big Sur 11.2.2 Expo环境下报红问题

### ISSUE THREAD

**Issue by zzb-bigboss** [czy0729/Bangumi#29]
一切操作都是按照说明来做的，但是启动报如下错误，请问可能是哪些地方引起的
![WechatIMG2](https://user-images.githubusercontent.com/54764793/139522702-6d0df269-87a8-417b-963c-ff9f204739a7.png)

**Comment by czy0729** [comment]
这个问题我前半个月应该弄了一个对策，在package.json里面
https://github.com/czy0729/Bangumi/blob/93ab24f7970c33f0c959064e2f0c9cee0269a0dc/package.json#L63

因为有些其他库也肯定用了这个包，那些库很老旧，所以我强制把源都改成这个，你还出现这个情况说明这个对策可能对某些机子不生效，这是我没料到的。

然后我把readme里面的删除了，我现在找回来，你可以试试：
** 遇到 undefined is not an object (evaluating '_this.view._component.measureInWindow') **

部分包使用了旧库，不想麻烦升级，所以把 components/@/react-native-safe-area-view/index.js 替换掉 node_modules/react-native-safe-area-view/index.js

**Comment by zzb-bigboss** [comment]
@czy0729 非常感谢您的帮助，但是在我构建的项目node_modules/react-native-safe-area-view路径下并没有index.js文件。我尝试将components/@/react-native-safe-area-view/index.js的代码替换掉node_modules/react-native-safe-area-view/index.tsx。但是依然没有解决问题
![WeChat8f50c747cb55ad94fc161c4836418b4f](https://user-images.githubusercontent.com/54764793/139531015-1ebb83d6-7d29-4c66-b6b4-87f0b51ea876.png)

**Comment by czy0729** [comment]
你试试把node_modules删掉，把lock文件删掉，用yarn安装不要用npm
