### ISSUE TITLE
做的可真不错

### ISSUE THREAD

**Issue by gladuo** [czy0729/Bangumi#3]
cdn 白嫖也是。。。机智
不过如果流量不大，可以考虑腾讯之类的 cdn，也有一些免费额度，应该体验会显著提高

**Comment by czy0729** [comment]
jsdelivr又是全球, 又有数据图表, 又能直接github提交, 又不需要实名, 国内的云就没优势咯, 主要还是不想学太多了, 本来就不应该有这样的写法, 只怪他实在太慢了
