### ISSUE TITLE
评论（吐槽)的两个问题(大概？

### ISSUE THREAD

**Issue by Freddd13** [czy0729/Bangumi#30]
1.现在已经 （在看） 状态的番，如果在里面添加或者更新评论并且还是 （在看），这个评论似乎发不出去？
2.我的空间里面每个动态有个❌，但是点了删除并没有删成功

**Comment by czy0729** [comment]
1. 这是哪里操作的，是条目评论的帖子不能添加回复？条目收藏更新可以？
2. 这个没做，我其实也知道的，待会看看是把按钮删掉还是直接把功能做上去，如果可以的话。

**Comment by Freddd13** [comment]
1是App首页进度里。奇怪的是有的番好像可以，但比如下图这个怎么更新都没结果
![Screenshot_2021-11-25-09-41-45-091_com.czy0729.bangumi.jpg](https://user-images.githubusercontent.com/50367552/143353449-00196ca6-dfbe-4827-ac73-8523311df2a3.jpg)

**Comment by Freddd13** [comment]
2没做就算了，只是昨天因为1试了一下发才发现的…不确定有没有这功能，不关键hh 你这作息太阴间了，注意身体

**Comment by czy0729** [comment]
我夜晚睡觉，半夜起床bgm38

**Comment by czy0729** [comment]
2 这个倒是处理了。
1 这个问题目前还没处理，主要是无法复现，若你可以稳定复现，可以再次打开这个issue。
