### ISSUE TITLE
「时光机」界面小bug

### ISSUE THREAD

**Issue by SamToki** [czy0729/Bangumi#31]
切换条目类别后，Tab栏内容不刷新，必须切换Tab才恢复正确显示。
例如：从「动画」切换至「音乐」，Tab仍然显示「在看」而非「在听」，数字也不刷新。从「在看」切换至「看过」后，恢复显示「在听」「听过」。
此外，此界面可下拉刷新，但没有任何UI提示（转圈之类的）。
![Screenshot_20211128_005446_com czy0729 bangumi](https://user-images.githubusercontent.com/73261908/143691316-c1e278f0-ac1a-498b-9b5c-9e113ca8401f.jpg)

**Comment by czy0729** [comment]
这界面应该不能下拉刷新才对啊，至少我没办法，压根我也没写。
这个刷新问题我昨天已经写好了，等下个版本发布。
另外你的状态栏为什么没透明，bgm38。

**Comment by SamToki** [comment]
> 这界面应该不能下拉刷新才对啊，至少我没办法，压根我也没写。 这个刷新问题我昨天已经写好了，等下个版本发布。 另外你的状态栏为什么没透明，bgm38。

大概是第一个条目与第二个条目上半部分，以这块区域为起点往下划一下，虽然没任何显示，但（等一两秒后）确实会刷新，看板娘的话也会变。
华为手机设定里有个隐藏刘海的选项，使状态栏始终黑底白字，并使app无视状态栏，不知道原生安卓有没有。个人挺讨厌刘海的，遇到没做好兼容的app，就经常给我遮住画面（比如全屏图片查看）。。。之前苹果电脑有了刘海，让我对苹果的好感几乎归零bgm38
