### ISSUE TITLE
从搜索进入作品页会重叠显示上一个页面

### ISSUE THREAD

**Issue by xtellaris** [czy0729/Bangumi#32]
## 截图
![Screenshot_20211207-172946](https://user-images.githubusercontent.com/40926741/145003892-c342c449-2a7c-4a7b-ac91-562849352fd8.jpg)
![Screenshot_20211207-172959](https://user-images.githubusercontent.com/40926741/145003909-562cc47a-fb7c-45f4-af40-9b4d7f975bff.jpg)

## 复现方法
1. 在主页右上角搜索后，选中某个结果进入作品页
2. 在作品页下滑，会出现搜索页的结果和底部bangumi娘banner与作品页的内容重叠在一起

## 环境
- 软件版本：v5.5.0，64位版本
- 系统：安卓10，魔趣类原生ROM

**Comment by czy0729** [comment]
我不知道现在的版本还有没这个问题，因为我的几个设备都无法复现。
这个版本我把导致这个问题的代码块提前了一下执行，不知道有没有效果，我也知道这个是什么问题，因为曾经在APP非常早期的时候出现过。

**Comment by xtellaris** [comment]
> 我不知道现在的版本还有没这个问题，因为我的几个设备都无法复现。 这个版本我把导致这个问题的代码块提前了一下执行，不知道有没有效果，我也知道这个是什么问题，因为曾经在APP非常早期的时候出现过。

我怀疑可能和酷安增量更新有关，因为在v5.6.0我又遇到过一个问题：进入超展开每个帖子的所有楼层的内容都只有“undefined”字样，而对该楼层的回复则能正常显示（我没有在5.6.0搜索过，所以不太清除是否还能复现本issue所说的重叠bug）；但我在所有渠道都没看到过类似问题；于是我清除了所有存储数据重新登录，这些问题不再出现了
听到你说这是早期bug重现，所以我猜想或许是增量更新的问题，因为我最近一直用酷安更新的app，而且应该都是增量更新；当然这是臆测，或许是我本地环境有什么问题

**Comment by xtellaris** [comment]
目前是v5.6.1，上述这些问题似乎都解决了
感谢你的辛勤debug，我去捐助一下hhh

**Comment by czy0729** [comment]
其实这个重叠问题还在，我跟某个酷友调试调了半天，找到问题了。
