### ISSUE TITLE
最新版本平板上点开软件在启动页横屏，而后进入主页竖屏

### ISSUE THREAD

**Issue by laoshuaibip** [czy0729/Bangumi#34]
设备小米平板5pro，被判断成不是平板了吗

**Comment by czy0729** [comment]
了解，我尽快修好

**Comment by 850710247liu** [comment]
目前在matepad11上也是这样 刚在酷安下载的5.6.2

**Comment by 850710247liu** [comment]
5.6.2只能竖屏显示 不知道是什么原因

**Comment by czy0729** [comment]
> 

居然有些安卓平板直接没那个isPad的值，去设置，然后滚动到底部，退出登录按钮下面的中间空白区域，摸几下，会进入开发页面，平台信息，希望可以复制给我看看

**Comment by laoshuaibip** [comment]
> 

{
  "__constants": {
    "isTesting": false,
    "Release": "11",
    "Model": "M2105K81AC",
    "reactNativeVersion": {
      "prerelease": null,
      "minor": 62,
      "major": 0,
      "patch": 3
    },
    "Version": 30,
    "uiMode": "unknown",
    "Fingerprint": "Xiaomi/elish/elish:11/RKQ1.200826.002/V12.5.8.0.RKYCNXM:user/release-keys",
    "Serial": "unknown"
  },
  "OS": "android",
  "Version": 30,
  "constants": {
    "isTesting": false,
    "Release": "11",
    "Model": "M2105K81AC",
    "reactNativeVersion": {
      "prerelease": null,
      "minor": 62,
      "major": 0,
      "patch": 3
    },
    "Version": 30,
    "uiMode": "unknown",
    "Fingerprint": "Xiaomi/elish/elish:11/RKQ1.200826.002/V12.5.8.0.RKYCNXM:user/release-keys",
    "Serial": "unknown"
  },
  "isTesting": false,
  "isTV": false
}

**Comment by 850710247liu** [comment]
{
  "__constants": {
    "isTesting": false,
    "Release": "10",
    "Model": "DBY-W09",
    "reactNativeVersion": {
      "prerelease": null,
      "minor": 62,
      "major": 0,
      "patch": 3
    },
    "Version": 29,
    "uiMode": "normal",
    "Fingerprint": "HUAWEI/DBY-W09/HWDBY:10/HUAWEIDBY-W09/102.0.0.219C00:user/release-keys",
    "Serial": "unknown"
  },
  "OS": "android",
  "Version": 29,
  "constants": {
    "isTesting": false,
    "Release": "10",
    "Model": "DBY-W09",
    "reactNativeVersion": {
      "prerelease": null,
      "minor": 62,
      "major": 0,
      "patch": 3
    },
    "Version": 29,
    "uiMode": "normal",
    "Fingerprint": "HUAWEI/DBY-W09/HWDBY:10/HUAWEIDBY-W09/102.0.0.219C00:user/release-keys",
    "Serial": "unknown"
  },
  "isTesting": false,
  "isTV": false
}

**Comment by 850710247liu** [comment]
{
  "__constants": {
    "isTesting": false,
    "Release": "10",
    "Model": "DBY-W09",
    "reactNativeVersion": {
      "prerelease": null,
      "minor": 62,
      "major": 0,
      "patch": 3
    },
    "Version": 29,
    "uiMode": "normal",
    "Fingerprint": "HUAWEI/DBY-W09/HWDBY:10/HUAWEIDBY-W09/102.0.0.219C00:user/release-keys",
    "Serial": "unknown"
  },
  "OS": "android",
  "Version": 29,
  "constants": {
    "isTesting": false,
    "Release": "10",
    "Model": "DBY-W09",
    "reactNativeVersion": {
      "prerelease": null,
      "minor": 62,
      "major": 0,
      "patch": 3
    },
    "Version": 29,
    "uiMode": "normal",
    "Fingerprint": "HUAWEI/DBY-W09/HWDBY:10/HUAWEIDBY-W09/102.0.0.219C00:user/release-keys",
    "Serial": "unknown"
  },
  "isTesting": false,
  "isTV": false
}

**Comment by 850710247liu** [comment]
好家伙 小米和华为的平板全没这个值 安卓平板好像也就这俩品牌了。。。。

**Comment by czy0729** [comment]
> 好家伙 小米和华为的平板全没这个值 安卓平板好像也就这俩品牌了。。。。

https://github.com/react-native-device-info/react-native-device-info 我找到了个能用的库，应该可以解决

**Comment by 850710247liu** [comment]
刚刚发布的5.6.3仍未解决该问题

**Comment by czy0729** [comment]
> 刚刚发布的5.6.3仍未解决该问题

麻了，安卓平板判断太不靠谱了

**Comment by czy0729** [comment]
> 设备小米平板5pro，被判断成不是平板了吗

请问这个版本你的Pad有没效果

**Comment by laoshuaibip** [comment]
> 

> > 设备小米平板5pro，被判断成不是平板了吗
> 
> 请问这个版本你的Pad有没效果

没有

**Comment by czy0729** [comment]
@850710247liu @laoshuaibip 
可以试一下这个
https://czy0729.lanzouq.com/iq6jky5uwmd

**Comment by laoshuaibip** [comment]
> 

这个可以了

**Comment by laoshuaibip** [comment]
> @850710247liu @laoshuaibip 可以试一下这个 https://czy0729.lanzouq.com/iq6jky5uwmd

这个我这里可以

**Comment by 850710247liu** [comment]
可以啦 感谢作者的跨年更新 辛苦～
