### ISSUE TITLE
561闪退

### ISSUE THREAD

**Issue by CberYellowstone** [czy0729/Bangumi#35]
架构：armv7，使用universe安装包安装
版本 561
设备安卓版本：7.0
表现：如图
![Screenshot_2021-12-20-23-43-22](https://user-images.githubusercontent.com/37031767/146794862-6c24d015-d348-4680-ac45-9a9ed461f786.jpg)

**Comment by CberYellowstone** [comment]
该问题在560版本已经存在

**Comment by czy0729** [comment]
我对错误做了个try catch，但是不知道是否js层面的问题，尝试一下5.6.2有没有这个问题

**Comment by CberYellowstone** [comment]
> 我对错误做了个 try catch，但是不知道是否 js 层面的问题，尝试一下 5.6.2 有没有这个问题

问题依旧

**Comment by CberYellowstone** [comment]
> 我对错误做了个 try catch，但是不知道是否 js 层面的问题，尝试一下 5.6.2 有没有这个问题

562截图
![image](https://user-images.githubusercontent.com/37031767/147381191-7634ca22-d110-4975-b151-0b4a4421acbb.png)

**Comment by czy0729** [comment]
我夜晚单独先打包7.0的包吧

**Comment by CberYellowstone** [comment]
> 我夜晚单独先打包 7.0 的包吧

晚上我会留意这个issue的

**Comment by czy0729** [comment]
其实这个功能os7.1就有了，我用的一个第三方包，他没控制好版本问题，我又没办法修

**Comment by CberYellowstone** [comment]
> 其实这个功能 os7.1 就有了，我用的一个第三方包，他没控制好版本问题，我又没办法修

看这个报错我也猜到是什么报错了, 7.0还没加入 长按桌面图标冒菜单 那个功能

**Comment by czy0729** [comment]
5.6.2我没有使用shortcuts了, 应该不会闪退
