### ISSUE TITLE
【BUG】播放页有两个bug

### ISSUE THREAD

**Issue by 850710247liu** [czy0729/Bangumi#36]
1.集数没有占满行，最后少了一个，65集跑到下一页了
2.“更新”这个按钮四边的深蓝没了 按钮不完整了

![Screenshot_20220113_051008_com.czy0729.bangumi.jpg](https://user-images.githubusercontent.com/59795360/149222069-b7c8a6ef-82a6-4edf-8292-2625625f820c.jpg)

**Comment by czy0729** [comment]
通常我开发根本没精力所有设备都测试一遍, 可以持续给我提这种问题

**Comment by 850710247liu** [comment]
辛苦啦

**Comment by czy0729** [comment]
最近一直改0.x时期的写法, 确实出了很多问题, 左右为难, 等我磨多几个版本就估计应该都好了

**Comment by 850710247liu** [comment]
> 最近一直改0.x时期的写法, 确实出了很多问题, 左右为难, 等我磨多几个版本就估计应该都好了

呜呜呜 大佬确实改了 但这回变成32了 比原来还少了4个。。。。
![Screenshot_20220126_114656_com czy0729 bangumi](https://user-images.githubusercontent.com/59795360/151100864-e66bed7e-3063-4d94-b298-6f4e159bcb9e.jpg)

**Comment by 850710247liu** [comment]
> 最近一直改0.x时期的写法, 确实出了很多问题, 左右为难, 等我磨多几个版本就估计应该都好了

呜呜呜 大佬确实改了 但这。。比原来的空还多了[笑哭]
![Screenshot_20220126_114857_com czy0729 bangumi](https://user-images.githubusercontent.com/59795360/151101009-50fde45b-9fb8-437b-bb8e-01a64054b34d.jpg)

**Comment by 850710247liu** [comment]
还有我的头像现在无法加载出来 只有第一次登录的时候加载出来了
这是平板ui的问题吗QAQ
![Screenshot_20220126_115040_com czy0729 bangumi](https://user-images.githubusercontent.com/59795360/151101292-eb39ce3d-425c-4ef0-935c-fd8b76b913d0.jpg)

**Comment by czy0729** [comment]
@850710247liu 头像还不见吗, 其实是不是换过, 说不定图床挂了
那个空我之前还以为你说没占满一排, 其实是数量占满, 我再改改, 问题不大

**Comment by 850710247liu** [comment]
> @850710247liu 头像还不见吗, 其实是不是换过, 说不定图床挂了
> 那个空我之前还以为你说没占满一排, 其实是数量占满, 我再改改, 问题不大

我想询问一个问题 该怎么加好友呢 有人要加我 但是在站内和app都没有找到同意按钮![Screenshot_20220127_184545_com.czy0729.bangumi.jpg](https://user-images.githubusercontent.com/59795360/151344184-e36ad167-43c3-46b8-93e7-7d710eeb06e8.jpg)

**Comment by czy0729** [comment]
他的空间里面右上方菜单可以加好友，占满这个问题我会记得再看看
