### ISSUE TITLE
求求你们换个LICENSE吧

### ISSUE THREAD

**Issue by li-guohao** [czy0729/Bangumi#37]
看到README文档里说是不能用于商业用途，但是一看你们的LICENSE，居然是MIT，我就很疑惑了，既然不能用于商业用途，为啥要用MIT许可协议？
不要再出现像faker.js那样的悲剧了
建议换成GPL许可协议

**Comment by czy0729** [comment]
写是那样写，假如真有能力拿了去商用我也不会管，管不了。。

**Comment by li-guohao** [comment]
> 写是那样写，假如真有能力拿了去商用我也不会管，管不了。。

真要到时候有人用你们的项目赚了不少钱，我相信你们心里肯定不舒服的，既然这样，为什么不一开始就使用GPL这种，至少到时候万一出事了，没有人指责你们用MIT协议还矫情(参考faker.js和log4j2)。
而且用GPL，也不妨碍你们出商业版授权等。

我是真心为你们这样的用爱发电的开源作者感到担心。

**Comment by czy0729** [comment]
这个项目第一行代码写下来就是不求任何回报，谢谢你的提醒。
