### ISSUE TITLE
【BUG】「时光机」分类 tag 显示 bug

### ISSUE THREAD

**Issue by heavenly-zy** [czy0729/Bangumi#38]
![image](https://user-images.githubusercontent.com/50657815/151131220-51e2bf74-2793-4ab1-ab62-459c170f8d32.png)
版本是用的最新的 5.7.1；切换到「三次元」分类的时候，就会像上图那样，这应该算是 bug 吧（bgm38），看上去像是因为宽度不够而换行了。

**Comment by czy0729** [comment]
草 bgm38

**Comment by heavenly-zy** [comment]
> 草 bgm38

居然秒回 bgm38

**Comment by czy0729** [comment]
有QQ邮件弹出来的啊b38

**Comment by heavenly-zy** [comment]
> 有QQ邮件弹出来的啊b38

![image](https://user-images.githubusercontent.com/50657815/151133352-ad1b4347-28b9-4315-8d46-a70b39d6da28.png)

还有一个小问题，就是所有的分类标签顶部都有一部分缺失

**Comment by czy0729** [comment]
知道晚上修，其实还发现了几个比这个严重得多的问题

**Comment by heavenly-zy** [comment]
> 知道晚上修，其实还发现了几个比这个严重得多的问题

辛苦啦(bgm24)
