### ISSUE TITLE
【bug】不清楚是不是bug，首次点开评论页等待时间超级长

### ISSUE THREAD

**Issue by WEIFZH** [czy0729/Bangumi#39]
首次点开评论页等待时间有个5、6秒，之后点开其他eposide的评论时间没有问题，已经更新到了最新版本。

**Comment by czy0729** [comment]
了解

**Comment by czy0729** [comment]
> > 了解
> 
> 还有个问题 就是在加载的过程中 软件完全卡住 连返回都做不到了 ><

卡住的问题我发现还存在, 我也查了很久都不知道哪里出了问题, 我再看看, 估计还是下大数据json的问题
