### ISSUE TITLE
Feature request: 片假名终结者

### ISSUE THREAD

**Issue by mmqmzk** [czy0729/Bangumi#4]
目前这个 app 的体验很好了, 但是跟浏览器比还差这个 user.js [片假名终结者](https://greasyfork.org/zh-CN/scripts/33268-katakana-terminator)

这个脚本可以利用翻译 api 给片假名加英语注释, 效果像这样
![image](https://user-images.githubusercontent.com/2217694/84001776-e7119100-a999-11ea-9d2c-bbd79517c7ce.png)

截图是桌面浏览器的, 安卓的 kiwi 浏览器也可以用

恳请考虑加这个功能

**Comment by czy0729** [comment]
我裂开了(bgm38)

**Comment by czy0729** [comment]
@mmqmzk 这个好难好难好难
html原生有这样的标签支持, 但是我APP这边查了一下完全没有
其次这个貌似是整个页面所有片假都生效? 还要涉及到我要怎么去分词去布局, 因为要做也只能自己布局

**Comment by KagurazakaHanabi** [comment]
找一个富文本的控件，其实自己实现也没有很难
分词的话看下那个脚本内容？

**Comment by czy0729** [comment]
@KagurazakaHanabi 有这样的控件我就不会裂开了, 当年找一个渲染富文本的花了九牛二虎之力, 然后还魔改了一大堆代码, 除非用webview, 当然我还是会看看怎么搞

**Comment by czy0729** [comment]
@mmqmzk 想了一下, App内其实日文感觉出现率还是很低的, 在App内是不可能像网页一样可以直接通过整个Dom遍历的, 必须一个一个文字组件去包裹你的逻辑

至于布局方面, 可能比较遗憾, 这个放置英文的地方必须自己为一行, 有可能位置对不上, 不过应该问题不大, 做是可以做的, 实际效果还是需要做的过程中才知道, 在做了.jpg

我主要想了解一下通常在什么地方会注意到

**Comment by mmqmzk** [comment]
不了解 react，是不同的文字组件都需要单独编码处理布局问题吗？
是否有可能在获取 bangumi api 数据的时候统一标记处理所有的 string 字段？
说错了勿怪。

**Comment by czy0729** [comment]
@mmqmzk 匹配片假名这个倒不是什么问题
单块文字不考虑换行的话,  放文字上方就可以了
主要是富文本嵌套文字, 这就真的头大, 夜晚看看怎么搞

**Comment by czy0729** [comment]
@mmqmzk 感觉真的做不了, 他本来就不支持这样的布局, 也无办法测量那个命中的片假名在什么具体位置
假如再右侧显示, 还能做一下, 不然碰到换行直接就没法了(bgm38)

**Comment by czy0729** [comment]
![image](https://user-images.githubusercontent.com/13514316/84914226-f3aa8d80-b0ed-11ea-8dbc-bbff3beab2a3.png)

@mmqmzk 想了个骚方法大概计算字体的位置... (bgm38)

**Comment by czy0729** [comment]
因为我之前写好了百度翻译, 暂时使用了百度翻译, 直接拿来就用, 不过我看见部分翻译没谷歌的合理
之后再添加谷歌的翻译系统吧, 今晚发布这个版本

**Comment by mmqmzk** [comment]
太棒了, 赞美大大! 😍

**Comment by czy0729** [comment]
@mmqmzk 百度翻译确实不咋的... 很多时候错翻

**Comment by mmqmzk** [comment]
@czy0729 嗯，英日翻译百度不行，还是得靠谷歌。
有些日本厂商的应该也可以，但是我不太清楚有哪些好的免费在线服务，只用过中日离线翻译的 jBeijing.
