### ISSUE TITLE
每个界面的第一张图片都无法加载

### ISSUE THREAD

**Issue by 850710247liu** [czy0729/Bangumi#40]
实测无论是使用哪个cdn 或者不开cdn都会出现这种情况
![Screenshot_20220127_195044_com.czy0729.bangumi.jpg](https://user-images.githubusercontent.com/59795360/151353669-b66b7aba-1f96-4ec8-83a1-829cfc8fe8b3.jpg)![Screenshot_20220127_195042_com.czy0729.bangumi.jpg](https://user-images.githubusercontent.com/59795360/151353676-2853df4a-15e1-4ace-848e-33ce513079cd.jpg)
![Screenshot_20220127_195551_com.czy0729.bangumi.jpg](https://user-images.githubusercontent.com/59795360/151354329-e4c43b44-04e3-46f6-b38a-bef570caaedf.jpg)
设备：matepad11

**Comment by czy0729** [comment]
怎么会这么怪, 理论上关掉CDN就没有任何相关逻辑, 都走网页的地址, 你试试网页版是不是看不见图片

**Comment by 850710247liu** [comment]
> 怎么会这么怪, 理论上关掉CDN就没有任何相关逻辑, 都走网页的地址, 你试试网页版是不是看不见图片

破案了 网页版一张图片都看不到 全是碎的
这是为什么呢。。。
![IMG_20220128_151718.jpg](https://user-images.githubusercontent.com/59795360/151503911-8a66ea42-cc32-4af1-b2e4-087b7e1651fa.jpg)

**Comment by czy0729** [comment]
这就代表你网络跟bgm的cloudfare cdn完全切割了, 我没什么办法
能改善的就是你app里面用cdn, 你可以选我的onedrive, 虽然有点慢, 至少能加载, 头像也要加速, 但是覆盖不了的图片也会走回去bgm的, 依然看不见

**Comment by 850710247liu** [comment]
> 这就代表你网络跟bgm的cloudfare cdn完全切割了, 我没什么办法
> 能改善的就是你app里面用cdn, 你可以选我的onedrive, 虽然有点慢, 至少能加载, 头像也要加速, 但是覆盖不了的图片也会走回去bgm的, 依然看不见

是的 我在北京哪里还一点事情没有呢 过年回老家就不行了^ 等我过一个月回北京的就应该没问题啦
