### ISSUE TITLE
打开特定小组讨论帖导致程序崩溃

### ISSUE THREAD

**Issue by SamToki** [czy0729/Bangumi#44]
https://bgm.tv/group/topic/367145
连续三次尝试打开这个帖子，程序崩溃，出现一个UI风格不太对劲的错误提示，而且还是英文的：
![Screenshot_20220204_011617_com czy0729 bangumi_487844965075035](https://user-images.githubusercontent.com/73261908/152409404-5121394d-fe7d-4626-ba0c-1cd434bf496d.jpg)
"embarrassing" (bgm38)

**Comment by czy0729** [comment]
OK，一眼感觉是#67的东西没解析对
