### ISSUE TITLE
新功能

### ISSUE THREAD

**Issue by A3148475824** [czy0729/Bangumi#48]
这款软件既然能记录看过的动漫,也能记录看了多少集,但是对于那些动辄几百集的,并且看过了去标记太难受了,能不能一键确认所有集都看过,还有豆瓣能不能导入？不能就算了

**Comment by czy0729** [comment]
一键确认所有请使用[章节]下方的输入框, 自己填数字提交
豆瓣导入实际编程起来巨麻烦, 基本不考虑, 章节能对得上都够呛了. 
bilibili导入受众会高得多, 有在计划中.

**Comment by A3148475824** [comment]
哔哩哔哩也行,腾讯优酷爱奇艺有打算吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月5日(周六) 晚上8:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [czy0729/Bangumi] 新功能 (Issue #48)




 
一键确认所有请使用[章节]下方的输入框, 自己填数字提交
 豆瓣导入实际编程起来巨麻烦, 基本不考虑, 章节能对得上都够呛了.
 bilibili导入受众会高得多, 有在计划中.

**Comment by czy0729** [comment]
大概不会计划bilibili之外的平台同步
因为其实已经涉及到过多的第三方元素了, 我一个人根本不可能维护得来, 这些第三方平台只要改一次, 我的功能就会失效, 而且除了bilibili之外的平台, 能同步动漫其实很少的

**Comment by A3148475824** [comment]
你代码能不能优化一下,改删减就删减,改修复就修复太卡了,不流畅



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月6日(周日) 凌晨0:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [czy0729/Bangumi] 新功能 (Issue #48)




 
大概不会计划bilibili之外的平台同步
 因为其实已经涉及到过多的第三方元素了, 我一个人根本不可能维护得来, 这些第三方平台只要改一次, 我的功能就会失效, 而且除了bilibili之外的平台, 能同步动漫其实很少的

**Comment by czy0729** [comment]
不流畅这个点我长期都在想怎么解决掉，无非就是切页动画不流畅。
至于网络请求卡也会很大程度影响流畅度，因为这个网站是国外服务器的，假如请求卡我也没什么办法。

**Comment by czy0729** [comment]
这小破网已经是一个运营了长达10多年前老旧垃圾山了，真要快起来还得等这个站点的人重构，这事已经在进行了。

**Comment by A3148475824** [comment]
哈哈哈😁



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月6日(周日) 凌晨0:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [czy0729/Bangumi] 新功能 (Issue #48)




 
这小破网已经是一个运营了长达10多年前老旧垃圾山了，真要快起来还得等这个站点的人重构，这事已经在进行了。

**Comment by A3148475824** [comment]
能上架谷歌商店吗？我看到有好几个第三方客户端都上架了,https://github.com/edwardez/bangumin



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月6日(周日) 凌晨0:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [czy0729/Bangumi] 新功能 (Issue #48)




 
这小破网已经是一个运营了长达10多年前老旧垃圾山了，真要快起来还得等这个站点的人重构，这事已经在进行了。
