### ISSUE TITLE
关于小圣杯的几个已知问题

### ISSUE THREAD

**Issue by sanbuexpress** [czy0729/Bangumi#5]
1. 在时间做差的时候 ( 如 ico 倒计时，资金日志中时间戳等 ) , 忽略了时差可能带来的计算错误.

2. 我的持仓 > ico 页面中所有的等级状态一直停留在 lv1.

3. 生成塔图的时候, 如果主席没有修改角色默认头像, 可能会有默认头像高度过高的情况. 这里网页端的做法是对其顶部适应宽度. 而客户端里是直接对其中部, 就导致了塔图角色断头以及与网页端塔图不统一的问题.

4. 现版本 ico 最低人数是 15, 而客户端上是 10.

**Comment by czy0729** [comment]
时差问题我记住, 下个版本看看
2, 3, 4问题已修复, 今晚发布
