### ISSUE TITLE
“推荐界面”卡顿异常

### ISSUE THREAD

**Issue by redapple0204** [czy0729/Bangumi#50]
iOS端和android端都有这个情况。具体的表现为切换到第五页之后点击下一页要卡很久（大概10s）才能切换到下一页，而且这个时候点击推荐列表的项目也要等10s以上才可以打开详情界面。

但是如果只是刚开软件点进其他地方，或者是翻推荐第一二页就不会出现这样的状况。

**Comment by redapple0204** [comment]
此外，还有非常诡异的跳页问题。例如我翻到15页，放他一段时间突然会跳到第一页。或者是突然从”相似“跳到”不同“

**Comment by czy0729** [comment]
谢谢反馈，这个页面数据太多，很难处理，目前我在努力优化切页动画不流畅得问题，我会找时间重构掉的
