### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by owen800q** [czy0729/Bangumi#51]
Env: Mac 10.15
node version: 16.11.1

(node-16.11.1) kwan@WINGs-MacBook-Pro Bangumi % npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: undefined@1.0.0
npm ERR! Found: react-native-screens@3.0.0
npm ERR! node_modules/react-native-screens
npm ERR!   react-native-screens@"~3.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react-native-screens@"^1.0.0 || ^1.0.0-alpha" from react-navigation-tabs@1.0.2
npm ERR! node_modules/react-navigation-tabs
npm ERR!   react-navigation-tabs@"1.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/kwan/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:

**Comment by czy0729** [comment]
用yarn可以安装，或者用npm 的 --force安装

**Comment by owen800q** [comment]
@czy0729  --force 不行，resolve不了react-navigation 包, yarn 可以裝上了, 最近在学RN,  这个项目太强了，很适合学习RN生态和最佳实践

**Comment by czy0729** [comment]
这个项目最初的架构是3年前的了，特别是react-navigation@3的部分，你应该看最新的框架对应文档

**Comment by owen800q** [comment]
有什么值得参考的项目吗，主要是想多读读代码，跟着敲一遍, 有时看完文档后感觉跟没学一样😩

不像Vue和Flutter，感觉RN很少成品开源项目, Bangumi这个感觉是中文社区唯一一个了
