### ISSUE TITLE
出现页面重叠现象

### ISSUE THREAD

**Issue by 850710247liu** [czy0729/Bangumi#52]
![Screenshot_20220316_222327_com.czy0729.bangumi.jpg](https://user-images.githubusercontent.com/59795360/158612312-b63c572a-3a25-421b-8890-4453ff0fca04.jpg)
而且垂直切页也不好使了><

**Comment by czy0729** [comment]
页面动画忘记把之前的写回去了，还能增加几种新类型的切页。
这个重叠的问题，是不是你之前加我QQ联系过的那位啊，是的话QQ可以说，不过我今天有点累，等我玩一会再修

**Comment by 850710247liu** [comment]
> 页面动画忘记把之前的写回去了，还能增加几种新类型的切页。
> 这个重叠的问题，是不是你之前加我QQ联系过的那位啊，是的话QQ可以说，不过我今天有点累，等我玩一会再修

不是 我没加过你的qq 你应该记混了 (bgm38)

**Comment by czy0729** [comment]
这个问题我知道为什么，就是某个库升级后坏了

**Comment by 850710247liu** [comment]
> > 页面动画忘记把之前的写回去了，还能增加几种新类型的切页。
> > 这个重叠的问题，是不是你之前加我QQ联系过的那位啊，是的话QQ可以说，不过我今天有点累，等我玩一会再修
> 
> 不是 我没加过你的qq 你应该记混了 (bgm38)

不着急 我回退了 用adb把旧版本装了><
