### ISSUE TITLE
页面白屏

### ISSUE THREAD

**Issue by 850710247liu** [czy0729/Bangumi#53]
![Screenshot_20220316_222720_com.czy0729.bangumi.jpg](https://user-images.githubusercontent.com/59795360/158612834-ee0be30a-7e89-461c-a27b-8600babdcb94.jpg)
在日志页点评论 页面会白屏
![Screenshot_20220316_222714_com.czy0729.bangumi.jpg](https://user-images.githubusercontent.com/59795360/158612843-b9782007-5ceb-45c0-8fd9-836823b89b24.jpg)
而且上个版本这个页面是居中的 平板上看很舒服 这回全屏看着很难受

**Comment by 850710247liu** [comment]
而且没点开的时候，右下角的小飞机和我要吐槽四个字没有一行 串了

**Comment by czy0729** [comment]
pad模式我还没对症下药过(bgm38) 你可以的话直接加我个QQ直接说方便点402731062
