### ISSUE TITLE
小说页面出现问题

### ISSUE THREAD

**Issue by shangguan6636** [czy0729/Bangumi#54]
![Screenshot_2022-03-24-12-25-54-491_com.czy0729.bangumi.jpg](https://user-images.githubusercontent.com/44657091/159842518-79f7f077-506c-4251-875f-185c80cad26b.jpg)

**Comment by czy0729** [comment]
昨天已经修好了
https://github.com/czy0729/Bangumi/commit/6af43ca4caddaf94f7aa2efe4a790c40f9ef3127
会在近2天内发布这个版本
