### ISSUE TITLE
点击帖子内容中带下划线的条目超链接后崩溃

### ISSUE THREAD

**Issue by Freddd13** [czy0729/Bangumi#55]
![IMG_20220324_224052.jpg](https://user-images.githubusercontent.com/50367552/159941233-e3708f33-3a68-4cfd-847e-4358feb183a6.jpg)

之前以为是别人帖子内容里就有超链接，最近自己也发过帖后感觉是app缓存了打开过的条目然后提供个超链接？（不太清楚bgm38

不管怎样，上个版本好像还正常，今天发现点击帖子中任何一个这种黑色下划线的链接都会崩掉…

**Comment by czy0729** [comment]
确实 麻了
