### ISSUE TITLE
小圣杯卡顿

### ISSUE THREAD

**Issue by vaecebyZ** [czy0729/Bangumi#56]
描述：
  当小圣杯持仓超过1300或者1400时候页面开始疯狂掉帧卡顿，直接无法正常使用。
设备：
  onePlus9 
版本：
  6.1.1

**Comment by czy0729** [comment]
持仓页面一进去就卡死了吗？是不是显示的总览tab？

**Comment by vaecebyZ** [comment]
> 

切换tag和点击人物或者圣殿之后就一直无响应，或者点击进去后就无法返回。视频：[https://sanka.sbs/bgm1.mp4](https://sanka.sbs/bgm1.mp4)
[https://sanka.sbs/bgm2.mp4](https://sanka.sbs/bgm2.mp4)

**Comment by vaecebyZ** [comment]
> 持仓页面一进去就卡死了吗？是不是显示的总览tab？

切换tag和点击人物或者圣殿之后就一直无响应，或者点击进去后就无法返回。视频：[bgm1.mp4](https://sanka.sbs/bgm1.mp4)
[bgm2.mp4)](https://sanka.sbs/bgm2.mp4)

**Comment by vaecebyZ** [comment]
新版本没发现这个问题了关闭了。
