### ISSUE TITLE
用户信息请求失败，拉取收藏进度失败

### ISSUE THREAD

**Issue by mapleleaf9629** [czy0729/Bangumi#59]
登陆后不知为何拉取收藏失败，各种登陆方式都用过了，网络探针检测也都是正常的，挂了VPN之后一切正常。
目前版本为6.1.3，之前也有出现过这样的问题，但是很少，但是更新之后完全用不了了，只要点登陆就会请求失败。有人知道是什么问题么？
![Screenshot_2022-04-16-10-14-50-421_com.czy0729.bangumi.jpg](https://user-images.githubusercontent.com/33835756/163657763-e32b53f6-a2d9-4b82-a7fa-662a0624f67a.jpg)

**Comment by czy0729** [comment]
跟你网络有关系，有时候网络会完全访问不到bgm.tv，假如wifi不可以流量可以的话，相反也是，可是证实。
通常无解，也许过几个小时又会恢复正常。
