### ISSUE TITLE
时光机页面标题样式问题

### ISSUE THREAD

**Issue by amzrk2** [czy0729/Bangumi#6]
## 状态

- Release v3.7.0
- Android 10 (MIUI 11.0.8)
- 红米 K20 Pro PE (1080x2340 DPI 392)

## 详情

看图说话即可（

![Screenshot_2020-06-27-21-05-32-390_com.czy0729.ba.jpg](https://i.loli.net/2020/06/27/5lMBKCRWO1QeA9J.jpg)

**Comment by czy0729** [comment]
收到, 这里2个字体行高不一样很难搞, 而且第二行是折断的, 计算英文的时候很难知道是否原句子被折断了.

**Comment by czy0729** [comment]
还有MIUI12的字体会好看很多(bgm38), 我已经升级了
