### ISSUE TITLE
简转繁问题

### ISSUE THREAD

**Issue by david082321** [czy0729/Bangumi#60]
我知道简转繁会有一对多的问题，但是能不能将某些固定的文字 (例如app的设置页面的文字)，用人工翻译好的内容，而不是用软件简转繁。
~~而其他内容用简转繁的只是偶尔看一次还能勉强接受，设置页面每次要更新的时候都会进去看到。~~

例如设置里的「画面」，正确应该用「畫面」，而不是用「畫麵」(Draw noodles)。

~~ps. 等于是希望能支持 i18n~~

补充：又或是能改进一下简转繁的程序，加入一些特定词的转换之类的。

**Comment by czy0729** [comment]
不用繁体，我也不知道那些是正确的，你可以把界面上的文字都列举出来，我做规避

**Comment by david082321** [comment]
# 转换出错：
畫麵→畫面
聯係→聯絡
係統→系統
係列→系列

# 用语不同：
登錄→登入
搜索→搜尋
設置→設定
緩存→快取
默認(default)→預設
默認(acquiescence)→默認
ex: 恢復默認(Reset default)→恢復預設

**Comment by czy0729** [comment]
谢谢 很专业！
