### ISSUE TITLE
有关自己搭建CDN加速的问题

### ISSUE THREAD

**Issue by t-satoru** [czy0729/Bangumi#62]
最近GFW各种阴间操作，导致jsDelivr爆炸并被废弃，这个我们只能默哀。
但是如果用OneDrive做图床技术上能够实现的话，能否开放OneDrive图床的下载，并拿来自己搭建用于bangumi的图床呢？（我自己用的话甚至还能拿世纪互联搭，快肯定快）
~~（当我问完这个问题我才意识到，拿几块钱打赏一下真的就这么难吗）~~

**Comment by czy0729** [comment]
白嫖没错, jsdelivr就是白嫖到底的最好实践, 目前其实还在调整, 你可以私信我个id, 我给你用协助测试
很可惜我也我花了挺多时间去研究并维护这套机制, 不过一夜就回到解放前
用户自定义图床并没有简单到能随便换个域名, 实际上面很不现实, 这种事情就算做也很容易开了个头就没后面

**Comment by MagmaBlock** [comment]
OneDrive图床会比较麻烦，总之必须得有后端
因为OD的链接有时效性
而且如果放在OD里面，从bangumi那边拉图片也挺麻烦的

**Comment by czy0729** [comment]
close
