### ISSUE TITLE
新增登录验证方式

### ISSUE THREAD

**Issue by lilyblessing** [czy0729/Bangumi#66]
BGM似乎可以手动生成个人令牌了，最长1年的有效时间。

![Snipaste_2022-06-19_15-10-58](https://raw.githubusercontent.com/lilyblessing/img/main/20220619/Snipaste_2022-06-19_15-10-58.2upty8udg2q0.webp)

app用的oauth授权token默认只有一周时间，是否可以增加用户手动输入自己token的方式来延长登录时间

![Snipaste_2022-06-19_15-12-02](https://raw.githubusercontent.com/lilyblessing/img/main/20220619/Snipaste_2022-06-19_15-12-02.79hkhddhvc80.webp)

新建&管理个人令牌的页面：https://next.bgm.tv/demo/access-token

关于个人令牌管理： https://bgm.tv/group/topic/370315

**Comment by czy0729** [comment]
由于1.0的api数据几乎残缺到无法用的程度, 其实在App开发很早期的阶段已经很少使用api了
目前App内80%的数据可能都来源于是爬的网页字符串解析出来使用
后面也有关注过新api, 然而新的也可能只覆盖到20-30%的样子, 依然有很多很有意义的数据没有

然后就是其实App内的过期我敢肯定基本都是网页cookie 7天过期导致的我不得不登出, 实际一直以来我观察到的access_token绝对不止7天, 关键还是网页版过期了

有一些新的api数据是有助于我替换掉网页数据的, 我已经有计划用上

**Comment by czy0729** [comment]
有一个更有益的方向是, 我看看能不能尽量少依赖网页数据, 而去令就算网页cookie过期了, 也依然可能使用上绝大部分功能.
