### ISSUE TITLE
每日放送与自定义更新时间逻辑混乱

### ISSUE THREAD

**Issue by Q16KBreak** [czy0729/Bangumi#68]
描述：如图，设定更新时间为周五 01:50 （25:50）收藏界面显示正常，但每日放送界面的时间线显示错误
![1657288517521](https://user-images.githubusercontent.com/51452206/178006068-f60b812f-85c7-418d-8056-ce5f12e29332.jpg)
![1657288517529](https://user-images.githubusercontent.com/51452206/178006078-fe05a5d6-9ccd-4982-95a1-15eb99e95505.jpg)
![1657288517536](https://user-images.githubusercontent.com/51452206/178006085-6342cf95-be62-47ad-b003-691e30474146.jpg)
希望可以加入30小时制开关
版本：6.5.0
设备：小米平板5

**Comment by czy0729** [comment]
好的问题可能会很快修复, 但是30小时我可能要好好研究下

**Comment by czy0729** [comment]
我感觉是不是你的APP没有冷启动过导致的? 是不是星期四一直开着到星期五了?

**Comment by Q16KBreak** [comment]
确实是冷启动的问题 重开一下就好了

**Comment by czy0729** [comment]
我优化下, 动态获取当前时间, 我没想过有人挂着不关的

**Comment by Q16KBreak** [comment]
辛苦你了
