### ISSUE TITLE
[feature]希望可以在收藏或者时光机界面 对番剧的观看状态 快速切换

### ISSUE THREAD

**Issue by sena-nana** [czy0729/Bangumi#69]
## 问题：
目前管理番剧观看状态，需要点进每个番剧的详情信息再切换，由于加载速度较慢，每个番剧需要数秒才能完成该操作，对于需要进行大量管理操作的时候非常麻烦
## 方案
在收藏或者时光机，针对番剧的管理界面。添加一个按钮用于快速切换番剧为已看，在看，想看。简化用户操作流程。该按钮在没有追番时，也可用于快速设置为想看状态。
对于书籍和音乐，由于状态类型共通，也可以适用于这种操作
## 替代方案
也可以通过长按，弹出选项菜单来切换状态。但是相比于按钮单次操作时间更长
左右滑动进行切换比较符合任务交互逻辑，但是会与界面切换相冲突

**Comment by sena-nana** [comment]
抱歉，我是baka，点了一圈发现那个星星就是这个功能

**Comment by czy0729** [comment]
当前版本其实绝大部分页面都已经做上了这个功能

**Comment by sena-nana** [comment]
> 当前版本其实绝大部分页面都已经做上了这个功能

在前几次更新就注意到了，现在很方便。真的辛苦了
