### ISSUE TITLE
用户评分的显示不正常

### ISSUE THREAD

**Issue by amzrk2** [czy0729/Bangumi#7]
没错又是我（😛
用户评分的显示，小数部分消失。
更新完 MIUI12 出现的问题，**原生 7.0** 模拟器**无法复现**，以下截图左侧为实机右侧为模拟器：
实机：MIUI12 1080x2340 392DPI；模拟器 1620x810 240DPI；实机版本 3.7.1酷安；模拟器版本 Release 内 armeabi-v7a 包

截图：
![0001.jpg](https://i.loli.net/2020/06/30/mBn2cXGPgSs7qUy.jpg)

**Comment by czy0729** [comment]
要询问的问题:
是否有改过开发者模式里面的默认dpi
是否原生的小米兰亭pro字体
是否有试过调整过设置里面的字体增大缩小
这问题我了解到时出现在加粗字体上面, 是否只有加粗的小数会被截取

这问题有看见过别人遇到过, 但是我自己没碰到过, 我是小米10 miui12

**Comment by amzrk2** [comment]
系统是三清重新从头刷的
开发者模式启动，仅改过USB调试用于实机调网页，DPI没动过
原生的小米兰亭pro，默认大小，默认粗细，没改动过

新发现：
在字体设置里面把字体粗细改成 细：恢复正常
字体粗细改回 细：依旧正常
重启手机（粗细为默认）：问题复现
重启手机（粗细为细）：问题复现

只要在设置内调整过字体粗细（无论调成什么），再打开应用就一切正常
重启手机后就又出现了
MIUI 是稳定版 12.0.2，可能是小米的问题？

**Comment by czy0729** [comment]
通常改动的系统设置只要影响到app内的样式, 按道理app都会卡死, 这是框架的问题
你是开着app改过字体粗细? 假如是可能要重启app, 我自己也看看吧, 我也是稳定版

**Comment by amzrk2** [comment]
嗯，是干掉后台再重启app，开着改字体直接切回去会直接停止响应

**Comment by czy0729** [comment]
目前这个版本你这2个issue还有哪个问题, 我自己无法复现, 只是猜着改的

**Comment by amzrk2** [comment]
这边数字的显示都没问题了，那边英文原词标注的话平时也用不上所以只打开试了一会、暂时没啥问题了🤗

issue 都 close 了
