### ISSUE TITLE
关于ipa文件

### ISSUE THREAD

**Issue by THU-Pieris** [czy0729/Bangumi#71]
首先感谢6.4.2版本提供ipa，比expo运行快多了qwq。但是最近两个版本都没有提供，想问一下是以后不打算提供了，或者是有其它发布渠道，还是..?谢谢！

**Comment by czy0729** [comment]
因为用的人实在是太少了, 不多于5人, 可能是使用成本还是太高了. 
我夜晚看看打包一个.

**Comment by THU-Pieris** [comment]
> 因为用的人实在是太少了, 不多于5人, 可能是使用成本还是太高了. 
> 
> 我夜晚看看打包一个.

辛苦了！

**Comment by czy0729** [comment]
https://czy0729.lanzouq.com/imohS082p1pc
https://czy0729.lanzouq.com/iGkbw082p21e

后缀改成 bangumi-v6.6.0-archive.ipa.zip.001  和 002
我打包好还没安装过, 请你测试一下, 哈哈

**Comment by czy0729** [comment]
草, 这搜索有条线, 我一直黑暗模式的, 没发现

**Comment by THU-Pieris** [comment]
阿这，我的本意只是截个版本号qwq

**Comment by czy0729** [comment]
我也不是那个意思, 没问题的话, 我去更新文档了
