### ISSUE TITLE
GitHub Actions 打包ipa 文件

### ISSUE THREAD

**Issue by DevCoz** [czy0729/Bangumi#73]
大佬，你可以用GitHub Actions打包ipa文件，这个方便你更新安装包。

**Comment by czy0729** [comment]
打包还得二步认证呢, 何况号都是借来的
通常是2版本更新一次 ipa, 其实1个版本的更新量是很少的

**Comment by czy0729** [comment]
其实是用 ipa 的人太少了, 我看见下载量只有4, 多点我就会1版本打包1次, 打1次挺麻烦的

**Comment by DevCoz** [comment]
好的，谢谢

**Comment by czy0729** [comment]
已打包，若安装过望告知有没有出问题

**Comment by DevCoz** [comment]
已经下载，安装谢谢。

**Comment by mlyxshi** [comment]
纯iOS React-Native 打包应该不需要付费账号吧(VPN 相关要注册公司之类)？Altstore会2次签名。GitHub Actions 自动 build release ipa 非常复杂吗？ ~~想一直用最新版~~

**Comment by czy0729** [comment]
> 纯iOS React-Native 打包应该不需要付费账号吧(VPN 相关要注册公司之类)？Altstore会2次签名。GitHub Actions 自动 build release ipa 非常复杂吗？ ~想一直用最新版~

主要是我用的 expo 开发导致现在这种情况, 我在享受 expo 这个框架给与我的开发优势, 理论上他是允许你无账号打包的, 但是他不知道什么原因就是必须要. 假如你想无账号打包, 又需要从 expo 里面脱离出来, 脱离了他里面的库就不能使用了.

其实就是我懒了, 我马上给你打一个, 其实也就打2行命令...

**Comment by mlyxshi** [comment]
> 其实就是我懒了, 我马上给你打一个, 其实也就打2行命令...
这个可以搞个自动化吗

**Comment by czy0729** [comment]
> > 其实就是我懒了, 我马上给你打一个, 其实也就打2行命令...
> 
> 这个可以搞个自动化吗

目前我这种开发流程不能自动化, 我并不想放弃expo 带来的云调试云开发, 我现在可以连 iOS 环境都不需要就能开发和打包 ipa

**Comment by mlyxshi** [comment]
> > > 其实就是我懒了, 我马上给你打一个, 其实也就打2行命令...
> > 
> > 
> > 这个可以搞个自动化吗
> 
> 目前我这种开发流程不能自动化, 我并不想放弃expo 带来的云调试云开发, 我现在可以连 iOS 环境都不需要就能开发和打包 ipa

明白了，Altstore现在在搞trustsource，可能以后Altstore用户会多点吧。

**Comment by czy0729** [comment]
@mlyxshi https://exp-shell-app-assets.s3.us-west-1.amazonaws.com/ios/%40bgm-ios-test/bangumi-pro-f549773a-2b98-4210-a3e1-4227ec0cbec6-archive.ipa
