### ISSUE TITLE
什么时候可以启动原神

### ISSUE THREAD

**Issue by misaka10384** [czy0729/Bangumi#74]
什么时候可以用这个软件启动原神(bushi

**Comment by czy0729** [comment]
所以在APP启动会比在桌面启动要快吗 XD

**Comment by czy0729** [comment]
新版本有个可以指定条目跳转到特定URI的功能，没试过感觉就是输入 genshin:// 跳转? 崩坏3 是 bh3rd://
当然这功能并不是为了关闭这个而开发的 XD，我玩的国际服所以那些什么bot能支持吗

**Comment by misaka10384** [comment]
完了  不会用  不如说根本没找到这个功能在哪
