### ISSUE TITLE
网站评分排序方式不起作用

### ISSUE THREAD

**Issue by LingEmberMaple** [czy0729/Bangumi#76]
如题

**Comment by czy0729** [comment]
由于这个排序实际上是把所有条目先请求了再手动排序，目前好多都改成了懒计算，大概要用新的方法实现

**Comment by czy0729** [comment]
https://github.com/czy0729/Bangumi/releases/tag/7.7.0 
[时光机] 修复并优化了按（网站评分）排序的表现
