### ISSUE TITLE
7.3.0无法删除收藏的条目

### ISSUE THREAD

**Issue by ICEL0v0** [czy0729/Bangumi#77]
![Screenshot_2022-11-16-16-57-54-259_com czy0729 bangumi](https://user-images.githubusercontent.com/22609780/202135291-c4626a0e-0b02-45a8-ab68-d0cbc135257a.jpg)

**Comment by czy0729** [comment]
可能要等一下，现在 bgm.tv 老是查找不到 DNS，删除的这个操作我用到了网页数据，可能是因为这个原因导致那个请求失败了，并没有提示，你可以试试重新启动或者多次出入，看看是不是还是无法删除？

**Comment by czy0729** [comment]
https://github.com/czy0729/Bangumi/commit/eff9fd87187a6e6f0727233c55b338f0d50ceda0
