### ISSUE TITLE
关于收藏界面《全部展开》按钮的问题

### ISSUE THREAD

**Issue by ldqs365** [czy0729/Bangumi#80]
收藏界面的全部展开按钮在点击以后，不会展开全部收藏条目的详情，只会展开部分，而全部收起则正常工作

**Comment by czy0729** [comment]
因为首页数据获取写法非常惰性，虽然是有点问题，但是不影响使用，而且不太好修，修好了反而会降低流畅性。
我有空再看看怎么处理。

**Comment by ldqs365** [comment]
好的，感谢开发者的回复
