### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by JoshYEn** [czy0729/Bangumi#81]
iOS, ver 7.5.2
![IMG_5378](https://user-images.githubusercontent.com/11255434/211154276-e1965a5e-49b3-4f7e-b66e-d52d06245539.png)

**Comment by czy0729** [comment]
了解

**Comment by czy0729** [comment]
可以试一下最新的ipa，我手上没设备测试

**Comment by mlyxshi** [comment]
最新ipa没问题

**Comment by czy0729** [comment]
> 新版本是没有改版本号？还是5.7.2

这xcode都不知道怎么搞的，可以去看看找番剧里面，更新日期是多少，如果是2023年那整体代码肯定是最新的

**Comment by czy0729** [comment]
可以试试最新的 7.6.0，因为我也头一次设置这些东西，居然还要手动配置

**Comment by czy0729** [comment]
https://github.com/czy0729/Bangumi/releases/tag/7.7.0
