### ISSUE TITLE
[建议] 优化每日放送的显示时间

### ISSUE THREAD

**Issue by Ukenn2112** [czy0729/Bangumi#85]
- 检测用户设备时区 ~~关照海外追番同胞（~~

   希望检测用户系统时间时区，使放送时间随时区变化。

- 关于数据时间来源

   我猜测您应该使用的是来自 [bangumi-data](https://github.com/bangumi-data/bangumi-data/blob/master/data/items/2023/01.json) 的数据
   由于外层的 `begin&broadcast` 是日本电视台的放送时间与大多数追番人所观看的网络放送的时间有些许差距，希望可以设置优先显示来自 [sites](https://github.com/bangumi-data/bangumi-data/blob/master/data/items/2023/01.json#L22-L39) 内的 `begin&broadcast` 各大网络放送平台时间。

**Comment by czy0729** [comment]
放送时间就算是同一时区里面的不同 sites 差距也大，更不用说还要加上时区计算。
其实我一直不敢把时区的逻辑引入 app，但是这个问题一直是在日程上面的，就等人来反映。
https://bgm.tv/settings 网页里面是有时区设置的，我额可以读一下这个设置，假如你是日本，比中国早1小时，我可以简单点把所有的默认放送都 +1h，可能简单点。

**Comment by Ukenn2112** [comment]
刚看了下 bgm API 以及 bangumi-data 大多数时间数据都是 `ISO 8601 UTC` 格式，我觉得您后续可以将所有时间数据都统一转换成这个格式方便读取以便时区的处理 

下面是我先读取 bangumi-data 的 sites 内的数据，读到第一个数据就跳出并转换为日本时区 所排序的时间表（右）与 某站已转换日本时区的 网络放送的时间表（左）的比对，发现正确率还是挺高的

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/60847880/217277040-8e0fa224-9048-4ac1-bcc2-e94975a31c29.png">

**Comment by Ukenn2112** [comment]
刚刚在排序的时候还发现了一个问题

对于跨季（半年）番有遗漏的情况 如下图 `想要成为影之实力者！`，我觉得您可能需要读取 bangumi-data 最近半年或全部的数据 根据 [end](https://github.com/bangumi-data/bangumi-data/blob/master/data/items/2022/10.json#L433) 来判断完结

<img width="300" alt="image" src="https://user-images.githubusercontent.com/60847880/217282072-82d235fe-10ac-4d16-8013-10c10c670503.png"><img width="300" alt="image" src="https://user-images.githubusercontent.com/60847880/217282488-23f13b83-05ac-4dfd-99f7-5da0dcab7c65.png">

**Comment by czy0729** [comment]
https://www.yuque.com/chenzhenyu-k0epm/znygb4/umhqt99g5083yoso?singleDoc
目前大概改成是这样，不过也没进行过验证。

**Comment by Ukenn2112** [comment]
好的，辛苦了～，请问一下时区读取的是 https://bgm.tv/settings 里的么，还是会直接读取设备系统时区

**Comment by czy0729** [comment]
https://bgm.tv/settings 里面的时区实际上只影响到 html, 所以 APP 目前是直接读取设备系统时区
不过我感觉肯定也有人需要把外面例如超展开之类的那些时间都本地化

**Comment by Ukenn2112** [comment]
> https://bgm.tv/settings 里面的时区实际上只影响到 html, 所以 APP 目前是直接读取设备系统时区 不过我感觉肯定也有人需要把外面例如超展开之类的那些时间都本地化

那确实，那么全部统一时间格式就很有必要了

**Comment by czy0729** [comment]
其实最难的地方并不是这些，而是用户根本没这个概念，不理解为什么要这么做，甚至很多人连网页端与 APP 的关系都不知道。
你自动帮别人设置，有人可能不需要，你不设置了他们又不会自己去找的。
我目前打算是在设置里面加一个跟网页那个时区一样的，这样就能统一时区问题了。不过我还是想说绝大部分人从来没进去过设置页面，更不说找一个设置。

**Comment by Ukenn2112** [comment]
> 我目前打算是在设置里面加一个跟网页那个时区一样的，这样就能统一时区问题了。不过我还是想说绝大部分人从来没进去过设置页面，更不说找一个设置。

确实，用户教育和体验设计在应用开发中非常重要。即使你的应用有很多强大的功能，如果用户不理解或不知道如何使用它们，那么这些功能也发挥不到它的用处。

在一些功能位置上在用户第一次进入页面引导用户去进行设置，
例如这个每日放送：
我认为可以在在用户第一次进入这个功能页中弹窗说明本页的数据来源，并告诉用户放送时间时区默认设置的是系统时区，如需要更改可以跳转去调整时区设置。
