### ISSUE TITLE
[建议] 适配WSA界面

### ISSUE THREAD

**Issue by X012C** [czy0729/Bangumi#86]
一些UI在WSA中显得过大，且发现页出现偏移不显示全页现象。希望能够适配一下WSA的界面，支持双列或多列显示来解决屏幕尺寸变化带来的问题。
![image](https://user-images.githubusercontent.com/99554281/217772467-fe05976c-c2c3-486a-b798-24d5fd14f938.png)
![image](https://user-images.githubusercontent.com/99554281/217772752-fba9863f-9859-4a00-8ff4-15098ff7270d.png)

**Comment by czy0729** [comment]
本质还是根据手机设计，只是稍微兼容了一下至少能让东西看全。
要正常那要重新设计一套，上面截图的尺寸其实连最方的平板也不至于是这个长宽比。
目前统计WSA启动率连0.1%都没有。
暂时还是只能建议缩小屏幕尺寸来使用。
