### ISSUE TITLE
iOS bug

### ISSUE THREAD

**Issue by zsgvivo** [czy0729/Bangumi#87]
在点进某些帖子后会莫名白屏没法操作，只能退掉重启应用
例如我这里点进这个帖子 https://bangumi.tv/blog/317203 会稳定触发这个bug
iOS 版本 16.3
bangumi 版本 7.7.0 使用 altstore 侧载，我记得几个版本之前貌似没有这个问题

**Comment by zsgvivo** [comment]
白屏：
![IMG_A7F28EBA9190-1](https://user-images.githubusercontent.com/76935037/218260116-9438bdf6-4a78-42e9-8f4e-c927c09496f7.jpeg)

**Comment by czy0729** [comment]
https://github.com/czy0729/Bangumi/commit/0029266aa3418241cf22f8c9bceb8c90e601cb33
待 v7.7.2 发布
