### ISSUE TITLE
iOS更新Expo后无法打开App

### ISSUE THREAD

**Issue by caopeng000** [czy0729/Bangumi#89]
使用Tag 7.8.0的代码运行iOS 在Expo报错
![img_v2_e3ca4239-21dc-41f2-90ff-a86a152bec8g](https://user-images.githubusercontent.com/7322422/221334786-0e840782-67f4-4373-9ecb-dd4a5d0d86f9.jpg)
大佬帮忙看下吧

**Comment by czy0729** [comment]
试试最新的 master
