### ISSUE TITLE
关于目录编辑时光标的移动问题

### ISSUE THREAD

**Issue by northplus** [czy0729/Bangumi#90]
在编辑目录中的文字时，光标有时会出现错误移动的情况。
例如以下，当我删除文字中的0后，光标会直接跳动到2之前，而不是正常情况下的2之后
![Screenshot_2023-03-02-00-18-00-450_com czy0729 bangumi](https://user-images.githubusercontent.com/47496982/222199691-13f34cdc-c38c-4c0a-a713-0ed46f44ff6a.jpg)
![Screenshot_2023-03-02-00-18-09-769_com czy0729 bangumi](https://user-images.githubusercontent.com/47496982/222199692-4340d839-4a87-49c5-80f3-f7b3fd70071b.jpg)
希望有时间的话可以修一下这个bug。

**Comment by czy0729** [comment]
打算有空迭代整个模块，所以能网页修改尽量先用网页 (bgm38)
