### ISSUE TITLE
[反馈] ios底栏过高

### ISSUE THREAD

**Issue by Saber-ww** [czy0729/Bangumi#91]
设备为se3，ios16.3.1
![IMG_0288](https://user-images.githubusercontent.com/85892102/224485523-0a401ea3-e01f-4150-982e-9f89666d32f0.png)

**Comment by czy0729** [comment]
你这个是 IPA 还是 Expo，如果是 Expo 我能直接热更新的

**Comment by Saber-ww** [comment]
> 你这个是 IPA 还是 Expo，如果是 Expo 我能直接热更新的 话说 SE 底下是没有那条黑线的吗

ipa,黑线指啥，我再补个白色背景的

**Comment by Saber-ww** [comment]
![IMG_0289](https://user-images.githubusercontent.com/85892102/224486029-cebd99c1-10e8-4762-aa91-1cd14b141f41.png)

**Comment by czy0729** [comment]
手势那条线

**Comment by Saber-ww** [comment]
> 手势那条线

没有，非全面屏设备都没有

**Comment by czy0729** [comment]
https://github.com/czy0729/Bangumi/commit/c0dfb7a3b2981c4d5ec3631241ec07544d1d65cc

https://czy0729.lanzouf.com/iUMA20pvdd1e
下载后直接去掉 .zip 后缀，应该没问题
