### ISSUE TITLE
[建议]对不同的页面使用不同的Activity

### ISSUE THREAD

**Issue by meng-luo** [czy0729/Bangumi#95]
我想在MIUI平板上对该软件进行第三方的平行视界适配，需要使用activity来判断不同页面，然而这个软件的大部分的activity都是MainActivity

**Comment by czy0729** [comment]
抱歉，本人安卓原生知识几乎为0，并不理解你说的话。
你可以说得细一点，包括建议怎么做，想要什么效果，我可以与我懂安卓的朋友讨论。

**Comment by meng-luo** [comment]
Activity是指安卓的活动，应用在创建的时候通常会创建不同的Activity来达成不同的目的，一样应用的入口通常是MainActivity，然后通过按钮跳转到不同的Activity，可以简单的把Activity当做页面
