### ISSUE TITLE
[建议]能否基于搜索引擎实现对小组和帖子的搜索功能

### ISSUE THREAD

**Issue by zsgvivo** [czy0729/Bangumi#96]
比如google: site:bgm.tv xxx
对我来说是个挺常用的功能，电脑上可以直接google，手机就比较麻烦，如果app能提供搜索会方便很多

**Comment by czy0729** [comment]
假如大部分人都不能直接访问到google的话，这功能就没意义了啊

**Comment by zsgvivo** [comment]
> 假如大部分人都不能直接访问到google的话，这功能就没意义了啊

Google只是举个栗子，必应百度也可以，只要收录了bangumi的内容就搜得到

**Comment by czy0729** [comment]
我看看能不能做个反代吧，毕竟 google cse 好用
