### ISSUE TITLE
动画页面中日志点进去会白屏，下面吐槽有内容但是不显示

### ISSUE THREAD

**Issue by RhettButlerX** [czy0729/Bangumi#98]
首先感谢大佬开发。

我用的版本是iOS 7.9.0

使用时发现几个问题：
1.任何动画页面下，吐槽显示有几百＋，但是都不显示。
![IMG_2772(20230426-173527)](https://user-images.githubusercontent.com/20549449/234535793-6651e613-d1ec-405d-a651-37b5e27a86fd.PNG)

2.任何动画页面下，日志点进去，完整内容显示1秒后白屏。

https://user-images.githubusercontent.com/20549449/234535859-b27d956d-4911-42e6-874a-42daed247459.MP4

**Comment by czy0729** [comment]
以上问题已经是修复了的，目前 iOS IPA 最新是 7.11.2，Expo 是 7.12.1
