### ISSUE TITLE
【建议】时光机界面增加倒序排序

### ISSUE THREAD

**Issue by LockRim** [czy0729/Bangumi#99]
![Screenshot_20230501_141650_com czy0729 bangumi](https://user-images.githubusercontent.com/52944370/235415851-690eb69c-17ad-49e5-84f0-0612eefa23b7.jpg)
希望加一个倒序排序的按钮
方便看最早和评分最低

**Comment by czy0729** [comment]
其实加倒序也没多大用于，倒不如我看看如果加个分页
